### ISSUE TITLE
1.9 issues and new stuff

### ISSUE THREAD

**Issue by itpp16** [vozlt/nginx-module-vts#10]
with 1.9 I get a negative uptime value;
Version	Uptime	Connections	Requests
active	reading	writing	waiting	accepted	handled	Total	Req/s
1.9.0 -4293105030ms	1	0	1	0	57	57	212	0

any ideas? also can you have a look at the new 'streams' feature in 1.9 ?

**Comment by itpp16** [comment]
strange, restarted nginx and the negative value is gone, normal time now.

**Comment by vozlt** [comment]
To get the uptime is using the simple method which is process_start_time(json:loadMsec) - current_time(json:nowMsec) in built-in html.
If it is happening again, you need to check it(json:loadMsec and json:nowMsec in format/json).
Let me check it on the 'streams' later because of so busy now.

**Comment by centminmod** [comment]
thank you @vozlt this module is awesome and just what I was looking for. I've integrated it into my Centmin Mod LEMP stack installer's latest beta https://community.centminmod.com/threads/centmin-mod-nginx-live-vhost-traffic-statistics-preview-discussion.3022/ - works wonderfully with Nginx 1.9.1 :)

**Comment by itpp16** [comment]
It tool awhile to get back to this issue but this is a common json output when it goes wrong:
"loadMsec":4108553345,"nowMsec":20948346,
As you see loadMsec should remain static but at some point it is going negative and also starts to drift, might be a few days before I get back to the code to see why, might be a nginx internal value going bust.
![index](https://cloud.githubusercontent.com/assets/6222016/10087881/14f23468-6317-11e5-902e-61e05ac33d5b.jpeg)

**Comment by itpp16** [comment]
It is vtscf->start_msec going mad, no idea why. For the time being I'm pushing this static value onto the stack after 60sec and just use this value throughout runtime.

**Comment by vozlt** [comment]
I will check it soon.
Probably, It seem to be overflow of 32bit variables.
Is it a 32bit system?

-
###### The time variables(start_msec, now) in module is millisecond as follows:
`(seconds since 1970-01-01 00:00:00 UTC) * 1000`

###### So, In case of normal in json as follows:
```Json
{
.
.
"loadMsec":1443142379895,
"nowMsec":1443142397017`
.
.
.
```

###### The calculation of uptime second using json in html as follows:
`uptime = (nowMsec - loadMsec) / 1000`

**Comment by itpp16** [comment]
it is a 32bit system but in this variable case I don't think its an overflow because it happens anywhere after 3 days to 2 weeks (sometimes it never happens) and after it, it starts to drift (counting down negative). Either nginx is messing up this variable or the pointer gets invalid. ea. loadMsec(vtscf->start_msec) should be set once and stay static so it can't be an overflow issue.

**Comment by vozlt** [comment]
As you commented above: `"loadMsec":4108553345,"nowMsec":20948346,`
I think that the loadMsec in json was wrong because of smaller than 1420038000000(2015/01/01 12:00 to milliseconds)
Please check variable `maxIntegerSize` in json.

**Comment by itpp16** [comment]
It's not a maxsize issue, let me show you an example:
nginx starts:
"loadMsec":20948346,"nowMsec":20949346,
nginx is running for a while:
"loadMsec":20948346,"nowMsec":23212222,
nginx is still running for a while:
"loadMsec":20948346,"nowMsec":25333333,

So far as it should work, loadMsec is STATIC and NEVER changes.

At some point in time (3 days <-> 2 weeks) loadMsec (which is vtscf->start_msec) returns a negative value and you get:
"loadMsec":4108553345,"nowMsec":253444444,

The question is WHY is loadMsec (which is vtscf->start_msec) becoming negative while this is a static value which should not change?
I think it is a nginx value going bust, see also:
http://hg.nginx.org/nginx/rev/8c6e71722aff
Which is not related to this value but it might be a nginx value which isn't defined large enough, but that still does not explain why a static value changes (or its pointer gets lost).

**Comment by vozlt** [comment]
Just to be sure, Is nginx's worker process restart(not to master process)?
I was wondering whether each worker process's uptime is same or not at that point.

**Comment by itpp16** [comment]
It should be a master value as uptime can't be tied to a worker which can be restarted, crashed, reloaded, etc... Most of the time (99%) vtscf->start_msec is fine and stays static.
nb. a master can reload as well (binary replace function) but the master passes some values to the new master when this happens.

**Comment by vozlt** [comment]
OK, I understand but it still may be problem of nginx-module-vts.
If you are able to modify and test, then try as below:
```patch
--- ngx_http_vhost_traffic_status_module.c.org  2015-10-15 10:32:18.023029431 +0900
+++ ngx_http_vhost_traffic_status_module.c      2015-10-15 10:43:02.524150308 +0900
@@ -1849,7 +1849,7 @@ ngx_http_vhost_traffic_status_create_loc
         return NULL;
     }

-    conf->start_msec = (ngx_msec_t) (tp->sec * 1000 + tp->msec);
+    conf->start_msec = (ngx_msec_t) (tp->sec);
     conf->enable = NGX_CONF_UNSET;
     conf->shm_zone = NGX_CONF_UNSET_PTR;
     conf->format = NGX_CONF_UNSET;
```
And check whether json's loadMsec is changed or not.
If it was changed, then please let me know its values.(for checking actual time)
