### ISSUE TITLE
501 Not implemented

### ISSUE THREAD

**Issue by tadanki** [vozlt/nginx-module-vts#100]
Hi, 

vts seems to be unable to display status page for my setup as described below.
/status on the server endpoint returns a 501 not implemented.

```
nginx:
  Installed: 1.13.4-1-ppa7~trusty
  Candidate: 1.13.4-1-ppa7~trusty
  Version table:
 *** 1.13.4-1-ppa7~trusty 0
        500 http://ppa.launchpad.net/hda-me/nginx-stable/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.4.6-1ubuntu3.8 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.4.6-1ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

```

`Linux ip-###### 4.4.0-79-generic #100~14.04.1-Ubuntu SMP Fri May 19 18:36:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
I installed nginx and the module from the bundle at this ppa: 
```
sudo apt-add-repository ppa:hda-me/nginx-stable
sudo apt-get update
sudo apt-get install nginx nginx-module-vts

```
Nginx seems to come up fine, but I cannot seem to get status on the servers.
example server block from nginx.conf: 
```

load_module modules/ngx_http_vhost_traffic_status_module.so;

...
    server {
    	vhost_traffic_status on;
        listen 9089;
        server_name tag-measure.webservers tag-measure.webservers.*;
        # [metrics-tag]  tag-measure.webservers 9089
        location / {
            proxy_set_header HOST $host;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_connect_timeout 30;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://tag-measure.webservers;
        }

        location /status {
            vhost_traffic_status_bypass_stats on;
            vhost_traffic_status_display;
        }
    }

```

**Comment by semonsir** [comment]
I have the same problem. It had worked properly with nginx 1.8.0 before, but replied 501 when I updated nginx to 1.12.2. I need to use some new nginx feature and have to update nginx to a latest version. @vozlt Could u please help us?

**Comment by wazzzzzup** [comment]
You need to define [vhost_traffic_status_zone](https://github.com/vozlt/nginx-module-vts/#vhost_traffic_status_zone) manually, there is no default value in the current version. If it's not defined the module is disabled.

**Comment by spolnik** [comment]
I have exactly same problem for 1.12.2 - is there an plan to deal with it?

**Comment by Vovanys** [comment]
Faced the same problem. It turns out I forgot to add to the http block vhost_traffic_status_zone;

**Comment by vozlt** [comment]
Hi, I could not reproduce that issue(501 Not implemented) with the above settings.
I tested it in CentOS_7.x, (Nginx_1.12.2|Nginx_1.13.3), VTS_0.1.15.
Please let me know following informations you( @tadanki @semonsir @spolnik ) have run to confirm the issue(501 Not implemented):
1. Nginx version
2. nginx-module-vts version
3. nginx minimal settings to confirm the issue
4. OS verison

Thanks.

**Comment by semonsir** [comment]
thanks all.
My problem has fixed when I added http block vhost_traffic_status_zone.
It's really a great module !
