### ISSUE TITLE
is it possible to count response code individually?

### ISSUE THREAD

**Issue by prudnitskiy** [vozlt/nginx-module-vts#101]
In server zone we have a responses codes as a groups (1xx, 2xx etc). Is it possible to get detailed status? For 404, 401, 403 and so on?

**Comment by holgr** [comment]
I'd also love to be able to see more details on which response codes were given.

**Comment by vozlt** [comment]
Hi, The feature probably can be implemented using [`vhost_traffic_status_filter_by_set_key`](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_by_set_key) with [$status](https://nginx.org/en/docs/http/ngx_http_core_module.html#variables) variable(1.3.2, 1.2.2) in nginx.

As the below:
```Nginx
server {
  server_name example.org;
  vhost_traffic_status_filter_by_set_key $status $server_name:$server_port;
  ...
}
```
<img width="972" alt="screenshot-issue-101" src="https://user-images.githubusercontent.com/3648408/39913648-9c0145d2-553d-11e8-81d4-e2c72cfe9249.png">


Thanks.
