### ISSUE TITLE
Feature Request: Cache status

### ISSUE THREAD

**Issue by DBezemer** [vozlt/nginx-module-vts#11]
First of all great work on this module!

One of the things that would make this module even more awesome if you could add a cache status (efficiency, hits/misses) section to the output statistics as well.

Additionally do you think that you can tag various releases for easy integration when building packages?

**Comment by vozlt** [comment]
That's a good suggestion.

1. cache status
I'll do that when I get time.

2. tags
I am considering to tag or branch when adding new features such as tcp stream.

**Comment by vozlt** [comment]
I added cache status feature and had a tag v0.1.1.
You need to test if it works well or not.
It need deeper and many review by peoples.

latest commit: https://github.com/vozlt/nginx-module-vts/commit/d4aac91263598e7ecf4e83f54d767756dc68c394

**Comment by DBezemer** [comment]
Awesome, I will test it as soon as possible and get some reviews :)

**Comment by TrurlMcByte** [comment]
It's possible to add also in cache status count of used keys and, may be, usage of keys_zone memory?
