### ISSUE TITLE
Make Metrics more readable

### ISSUE THREAD

**Issue by strowi** [vozlt/nginx-module-vts#111]
Hi,

just a suggestion:
On our high-traffic nginx-load-balancer stats are showing up like "33643 GiB".

Wouldn't be straight forward to add "TiB" to the metrics?
Or add "." to the request-metrics?

Of course i agree usually we only check them in prometheus, but sometimes we need more real-time stats for debugging.

regards,
Roman

**Comment by vozlt** [comment]
I added it.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/f143f7d1803c28573b98f01cd86ccb06025df501
