### ISSUE TITLE
displaying upstream stats for remote backends ?

### ISSUE THREAD

**Issue by centminmod** [vozlt/nginx-module-vts#113]
Hi is there any solution for displaying the upstream stats for remote backends that do no reside on the server ?

thanks

**Comment by yastij** [comment]
this is merged here : https://github.com/hnlq715/nginx-vts-exporter/releases/tag/v0.10.0

@vozlt - can you bump the new version of the module please ?

**Comment by vozlt** [comment]
Sorry, I did not understand exactly what you say.
The servers in upstream group can be local or remote, isn't it?
Do you mean the aggregated statistics of remote servers using nginx-module-vts like issue https://github.com/vozlt/nginx-module-vts/issues/69?

**Comment by centminmod** [comment]
sorry for late reply but yes remote servers like that issue

**Comment by StrozhDima** [comment]
@vozlt Hi. I use nginx version 1.10.3 on debian. When I shutdown any server in upstream the state of this shutdowned server isn't changing. Status is always UP. But if I put the derective "down" in server line then the status is becoming "DOWN".

This is a part of my config:

`upstream elastic_cluster {
	ip_hash;
	server 192.168.0.2:9200 max_fails=3 fail_timeout=60;
	server 192.168.0.39200 max_fails=3 fail_timeout=60;
}`
