### ISSUE TITLE
Control doesn't work?

### ISSUE THREAD

**Issue by ximply** [vozlt/nginx-module-vts#117]
curl http://localhost:10000/status/control?cmd=reset&group=server&zone=localhost
response with {"processingReturn":false,"processingCommandString":"reset","processingGroupString":"","processingZoneString":"","processingCounts":0}

but localhost's data doesn't reset

**Comment by vozlt** [comment]
Hi, It needs to be wrap it in quotes.

Please try as follows:
`$ curl 'http://localhost:10000/status/control?cmd=reset&group=server&zone=localhost'`

Thanks.
