### ISSUE TITLE
Does it support Nginx 1.12.x

### ISSUE THREAD

**Issue by linbo** [vozlt/nginx-module-vts#118]
Does it support Nginx 1.12.x?

**Comment by DBezemer** [comment]
@linbo I think @vozlt has abandoned the project, and the module is currently known incompatible with nginx 1.12

**Comment by vozlt** [comment]
@linbo Yes, It is compatible up to nginx-1.14.0
@DBezemer Please let me know what is incompatible with nginx-1.12
Thanks.
