### ISSUE TITLE
Request Totals, Response Totals and Requests/sec are being counted twice in server_zones

### ISSUE THREAD

**Issue by WilliamDurin** [vozlt/nginx-module-vts#119]
I've been taking a look at metrics in VTS, and there appears to be an issue where requests are counted twice in server zones, but are correct at the upstreams.

https://www.screencast.com/t/QfAFLU3q
In this screenshot, take a look at the top Req/s for the whole server, it's 575. Then take a look at req/s for the server zones, it's 1146, which is double.

The top #, 575, is actually what is correct according to the other instrumentation I have.

**Comment by vozlt** [comment]
Hi, It is simply the sum of all `requestCounter` values in **serverZones** so that's the why.
Technically, I see no need to exist because total(*) in serverZones can be calculate by each **serverZones**.
Thanks.
