### ISSUE TITLE
They have changed response timings

### ISSUE THREAD

**Issue by itpp16** [vozlt/nginx-module-vts#12]
They have changed response timings in http://hg.nginx.org/nginx/rev/59fc60585f1e

ngx_http_vhost_traffic_status_module.c(476) : error C2039: 'response_sec' : is not a member of 'ngx_http_upstream_state_t'
        src/http\ngx_http_upstream.h(56) : see declaration of 'ngx_http_upstream_state_t'
ngx_http_vhost_traffic_status_module.c(476) : error C2039: 'response_msec' : is not a member of 'ngx_http_upstream_state_t'
        src/http\ngx_http_upstream.h(56) : see declaration of 'ngx_http_upstream_state_t'

Maybe:
//                (state[i].response_sec * 1000 + state[i].response_msec);
                (state[i].response_time * 1000 + state[i].response_time);

?

**Comment by vozlt** [comment]
Thank you for the information.
I have fixed it for the compatibility.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/3822810089ff211c3a4f8a630e36e78bb39b0b41

**Comment by itpp16** [comment]
Fix confirmed, tnx!
