### ISSUE TITLE
Can not catch nogroups part when vhost_traffic_status_dump has been added 

### ISSUE THREAD

**Issue by CHIENPINNWU** [vozlt/nginx-module-vts#123]
Hi there,

the problem as the title.

when if I'm setting `vhost_traffic_status_dump /var/log/nginx/vts.db` and nogroups capturer looks like is down. 

I noticed that the file size of the vts.db was grown to 603K and If I let the size down or reset the file and restart the NGINX somehow it works.

**Comment by vozlt** [comment]
Thanks for reporting.
What is your shared memory size using in `vhost_traffic_status_zone`?
If you set the default size(1M), try to increase the size to 32M(`vhost_traffic_status_zone shared:vhost_traffic_status:32m`).
If not, please let me know the nginx configuration and version to reprodce the problem.
