### ISSUE TITLE
Can this tool support TCP monitor?

### ISSUE THREAD

**Issue by owenJiao** [vozlt/nginx-module-vts#124]
This tool is very good to monitor HTTP traffic status, I want to know if It can monitor TCP traffic status ？
Thanks

**Comment by vozlt** [comment]
This relies on [nginx logging system](http://nginx.org/en/docs/http/ngx_http_log_module.html) as a module that works in the nginx subclass, so only HTTP protocol can be monitored such as status code(200, 404...), in/out bytes.
Thanks.
