### ISSUE TITLE
storage tab not showing

### ISSUE THREAD

**Issue by trs91km** [vozlt/nginx-module-vts#125]
PATH::/storage/vol is not showing status, please see my config below and advise

server{

location ~ ^/storage/(.+)/.*$ {
            set $volume $1;
            vhost_traffic_status_filter_by_set_key $volume storage::$server_name;
        }

location /status {
           vhost_traffic_status_display;
           vhost_traffic_status_display_format html;
           # kill cache
           add_header Last-Modified $date_gmt;
           add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
           if_modified_since off;
           expires off;
           etag off;
     }

}

**Comment by vozlt** [comment]
Once you access the url(http://{{hostname}}/storage/{{volume}}/...), it will be visible from then on.
```Nginx
server {
    server_name  debug.example.org;
    root         /home/httpd/vhosts/debug.example.org;

    location ~ ^/storage/(.+)/.*$ {
        set $volume $1;
        vhost_traffic_status_filter_by_set_key $volume storage::$server_name;
    }
}
```

```Bash
$ for i in {0..64}; do p=$((i%2)); curl -H 'Host: debug.example.org' http://localhost:1981/storage/vol${p}/${p}.txt; done
```

<img width="1028" alt="screenshot-issue-125" src="https://user-images.githubusercontent.com/3648408/40904683-779b5b88-6816-11e8-89c1-8acd4cc1a885.png">
