### ISSUE TITLE
Can I get error code like 499 not 4xx?

### ISSUE THREAD

**Issue by xujpxm** [vozlt/nginx-module-vts#127]
I love the  nginx-module-vts. Thank you so much. But I wonder If we can get the nginx error code like 499 not 4xx?

**Comment by vozlt** [comment]
See the below:

* https://github.com/vozlt/nginx-module-vts#to-calculate-traffic-for-detailed-http-status-code
* https://github.com/vozlt/nginx-module-vts/issues/101#issuecomment-388293006

Thanks.
