### ISSUE TITLE
Error nginx: [emerg] module "/usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so" is not binary compatible in /etc/nginx/nginx.conf:6

### ISSUE THREAD

**Issue by magnetogit** [vozlt/nginx-module-vts#128]
**Command** 
469  ./configure --with-compat --add-dynamic-module=../nginx-module-vts
 470  make module
 471  make modules
 472  make
 473  make install
 474  nginx -t

**Problem**
nginx: [emerg] module "/usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so" is not binary compatible in /etc/nginx/nginx.conf:6
nginx: configuration file /etc/nginx/nginx.conf test failed

**nginx -V**

root@ip-172-16-3-40:~/nginx-1.14.0# nginx -V
nginx version: nginx/1.14.0
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-ph1UVS/nginx-1.14.0/debian/modules/http-auth-pam --add-dynamic-module=/build/nginx-ph1UVS/nginx-1.14.0/debian/modules/http-dav-ext --add-dynamic-module=/build/nginx-ph1UVS/nginx-1.14.0/debian/modules/http-echo --add-dynamic-module=/build/nginx-ph1UVS/nginx-1.14.0/debian/modules/http-upstream-fair --add-dynamic-module=/build/nginx-ph1UVS/nginx-1.14.0/debian/modules/http-subs-filter

**Comment by magnetogit** [comment]
root@ip-172-16-3-40:/# find -name ngx_http_vhost_traffic_status_module.so
./home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so
./usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so
root@ip-172-16-3-40:/# md5sum /home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so
557bb1a8cf9b8c6fb3470a3128027c77  /home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so
root@ip-172-16-3-40:/# md5sum /usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so
557bb1a8cf9b8c6fb3470a3128027c77  /usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so

also i try load from  load_module "/home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so

user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
 load_module "/usr/local/nginx/modules/ngx_pagespeed.so";
#load_module "/usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so";
load_module "/home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so";

but same error
nginx: [emerg] module "/home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so" is not binary compatible in /etc/nginx/nginx.conf:7

**Comment by vozlt** [comment]
Probably it seems to be related to `--with-compat`.
Does it work well when you remove the `--with-compat` option?

**Comment by magnetogit** [comment]
same 

  505  cd objs/
  506  ls
  507  mv ngx_http_vhost_traffic_status_module.so ngx_http_vhost_traffic_status_module.so_bak
  508  ls -la
  509  mv ngx_http_vhost_traffic_status_module.o ngx_http_vhost_traffic_status_module.o_bak
  510  ls -la
  511  mv ngx_http_vhost_traffic_status_module_modules.c ngx_http_vhost_traffic_status_module_modules.c_bak
  512  mv ngx_http_vhost_traffic_status_module_modules.o ngx_http_vhost_traffic_status_module_modules.o_bak
  513  ls -la
  514  cd ..
  515  ./configure --add-dynamic-module=../nginx-module-vts
  516  make
  517  sudo make install
  518  cd objs/
  519  ls -la
  520  md5sum /home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so

root@ip-172-16-3-40:~/nginx-1.14.0/objs# md5sum /home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so
6cb35ae0e5b7a0cd470750d98dded7a1  /home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so



  522  nano /etc/nginx/nginx.conf

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
 load_module "/usr/local/nginx/modules/ngx_pagespeed.so";
#load_module "/usr/local/nginx/modules/ngx_http_vhost_traffic_status_module.so";
load_module "/home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so";

```
root@ip-172-16-3-40:~/nginx-1.14.0/objs# service nginx restart
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
root@ip-172-16-3-40:~/nginx-1.14.0/objs# nginx -t
nginx: [emerg] module "/home/ubuntu/nginx-1.14.0/objs/ngx_http_vhost_traffic_status_module.so" is not binary compatible in /etc/nginx/nginx.conf:7
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by vozlt** [comment]
Your nginx binary is already installed through package system and you are only trying to build the module, right?
When building, nginx-module-vts seems to have a different signature than the signature of the existing binary.
The signature string looks like `8,4,8,0011111111010111001111111111111111`. 
**Looking at the nginx source, even if you specify the --with-compat(`#define NGX_COMPAT 1`) option, the signature can vary.**
**In conclusion, you will have to compile the dynamic module with the same configure options as installed nginx binary.**
Thanks.

`$ grep 'NGX_COMPAT' objs/ngx_auto_config.h`
```Bash                                                                                                                                       
#ifndef NGX_COMPAT
#define NGX_COMPAT  1
```
`$ vi src/core/ngx_module.c`
```C
177     if (ngx_strcmp(module->signature, NGX_MODULE_SIGNATURE) != 0) {
178         ngx_conf_log_error(NGX_LOG_EMERG, cf, 0,
179                            "module \"%V\" is not binary compatible",
180                            file);
181         return NGX_ERROR;
182     }
```
`$ vi src/core/ngx_module.h`
```C
 21 #define NGX_MODULE_SIGNATURE_0                                                \
 22     ngx_value(NGX_PTR_SIZE) ","                                               \
 23     ngx_value(NGX_SIG_ATOMIC_T_SIZE) ","                                      \
 24     ngx_value(NGX_TIME_T_SIZE) ","
 25 
 26 #if (NGX_HAVE_KQUEUE)
 27 #define NGX_MODULE_SIGNATURE_1   "1"
 28 #else
 29 #define NGX_MODULE_SIGNATURE_1   "0"
 30 #endif
 31 
 32 #if (NGX_HAVE_IOCP)
 33 #define NGX_MODULE_SIGNATURE_2   "1"
 34 #else
 35 #define NGX_MODULE_SIGNATURE_2   "0"
 36 #endif
 37 
 38 #if (NGX_HAVE_FILE_AIO || NGX_COMPAT)
 39 #define NGX_MODULE_SIGNATURE_3   "1"
 40 #else
 41 #define NGX_MODULE_SIGNATURE_3   "0"
 42 #endif
 43 
 44 #if (NGX_HAVE_AIO_SENDFILE || NGX_COMPAT)
 45 #define NGX_MODULE_SIGNATURE_4   "1"
 46 #else
 47 #define NGX_MODULE_SIGNATURE_4   "0"
 48 #endif
 49 
 50 #if (NGX_HAVE_EVENTFD)
 51 #define NGX_MODULE_SIGNATURE_5   "1"
 52 #else
 53 #define NGX_MODULE_SIGNATURE_5   "0"
 54 #endif
.
.
200 #define NGX_MODULE_SIGNATURE                                                  \
201     NGX_MODULE_SIGNATURE_0 NGX_MODULE_SIGNATURE_1 NGX_MODULE_SIGNATURE_2      \
202     NGX_MODULE_SIGNATURE_3 NGX_MODULE_SIGNATURE_4 NGX_MODULE_SIGNATURE_5      \
203     NGX_MODULE_SIGNATURE_6 NGX_MODULE_SIGNATURE_7 NGX_MODULE_SIGNATURE_8      \
204     NGX_MODULE_SIGNATURE_9 NGX_MODULE_SIGNATURE_10 NGX_MODULE_SIGNATURE_11    \
205     NGX_MODULE_SIGNATURE_12 NGX_MODULE_SIGNATURE_13 NGX_MODULE_SIGNATURE_14   \
206     NGX_MODULE_SIGNATURE_15 NGX_MODULE_SIGNATURE_16 NGX_MODULE_SIGNATURE_17   \
207     NGX_MODULE_SIGNATURE_18 NGX_MODULE_SIGNATURE_19 NGX_MODULE_SIGNATURE_20   \
208     NGX_MODULE_SIGNATURE_21 NGX_MODULE_SIGNATURE_22 NGX_MODULE_SIGNATURE_23   \
209     NGX_MODULE_SIGNATURE_24 NGX_MODULE_SIGNATURE_25 NGX_MODULE_SIGNATURE_26   \
210     NGX_MODULE_SIGNATURE_27 NGX_MODULE_SIGNATURE_28 NGX_MODULE_SIGNATURE_29   \
211     NGX_MODULE_SIGNATURE_30 NGX_MODULE_SIGNATURE_31 NGX_MODULE_SIGNATURE_32   \
212     NGX_MODULE_SIGNATURE_33 NGX_MODULE_SIGNATURE_34
```

**Comment by pkiula** [comment]
@vozlt  I have compiled the dynamic modules with literally the options that configured nginx when installed via a simple `yum install nginx` (which currently installs nginx `1.18.0` on my Fedora 33). This is the command used: 

```
./configure $(nginx -V) \
     --with-compat \
        --add-dynamic-module=../ngx_brotli                      \
        --add-dynamic-module=../headers-more-nginx-module       \
        --add-dynamic-module=../ngx_security_headers            \
```

After making modules in a freshly downloaded 1.18.0 nginx folder, when I move them into the modules folder, I still see: 

```
# nginx -t 
nginx: [emerg] module "/usr/share/nginx/modules/ngx_http_security_headers_module.so" is not binary compatible in /etc/nginx/nginx.conf:16
nginx: configuration file /etc/nginx/nginx.conf test failed
```

This happens with or without compat. Any ideas what I may be missing?

**Comment by vozlt** [comment]
@pkiula 
Maybe on most systems the command(```nginx -V```) will contain not just pure options, but many other options like nginx version, gcc information, etc.
Please try to compile with explicit flags, not $(nginx -V).

```
$ nginx -V
nginx version: nginx/1.19.6
built by gcc 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
built with OpenSSL 1.1.1g FIPS  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=...
```

```
$ ./configure                                           \
     --with-compat                                      \
     --add-dynamic-module=../ngx_brotli                 \
     --add-dynamic-module=../headers-more-nginx-module  \
     --add-dynamic-module=../ngx_security_headers       \
     $(nginx -V 2>&1 | awk -F: '/configure/ {print $2}')
```
