### ISSUE TITLE
Customising html template ?

### ISSUE THREAD

**Issue by centminmod** [vozlt/nginx-module-vts#13]
I see the html template at https://github.com/vozlt/nginx-module-vts/blob/master/share/status.template.html. How would I go about customising the css after nginx-module-vts is installed ? Or would customisation need to be done before it's installed ?

**Comment by vozlt** [comment]
## To customize after the module installed
1. You need to change the `{{uri}}` string to your status uri in status.template.html as follows:
 ```
 shell> vi share/status.template.html
 ```
 ```
 var vtsStatusURI = "yourStatusUri/format/json", vtsUpdateInterval = 1000;
 ```

2. And then, customizing and copy status.template.html to server root directory as follows:
 ```
 shell> cp share/status.template.html /usr/share/nginx/html/status.html
 ```

4. Configure `nginx.conf`
 ```
    server {
        server_name YOURDOMAIN;
        root /usr/share/nginx/html;

        # Redirect requests for / to /status.html
        location = / {
            return 301 /status.html;
        }

        location = /status.html {}

        # Everything beginning /status (except for /status.html) is
        # processed by the status handler
        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format json;
        }
    }
 ```

4. Access to your html.
 ```
 http://YOURDOMAIN/status.html
 ```

## To customize before the module installed
1. Modify `share/status.template.html` (Do not change `{{uri}}` string)

2. Recreate the `ngx_http_vhost_traffic_status_module_html.h` as follows:
 ```
 shell> util/tplToDefine.sh status.template.html > src/ngx_http_vhost_traffic_status_module_html.h
 ```

3. Add the module to the build configuration by adding
  `--add-module=/path/to/nginx-module-vts`

4. Build the nginx binary.

5. Install the nginx binary.

**Comment by centminmod** [comment]
Cheers @vozlt used your 2nd method as outlined https://community.centminmod.com/posts/14130/

**Comment by Lecyd** [comment]
> ## To customize after the module installed
> 1. You need to change the `{{uri}}` string to your status uri in status.template.html as follows:
>    ```
>    shell> vi share/status.template.html
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    ```
>    var vtsStatusURI = "yourStatusUri/format/json", vtsUpdateInterval = 1000;
>    ```
> 2. And then, customizing and copy status.template.html to server root directory as follows:
>    ```
>    shell> cp share/status.template.html /usr/share/nginx/html/status.html
>    ```
> 3. Configure `nginx.conf`
>    ```
>      server {
>          server_name YOURDOMAIN;
>          root /usr/share/nginx/html;
>    
>          # Redirect requests for / to /status.html
>          location = / {
>              return 301 /status.html;
>          }
>    
>          location = /status.html {}
>    
>          # Everything beginning /status (except for /status.html) is
>          # processed by the status handler
>          location /status {
>              vhost_traffic_status_display;
>              vhost_traffic_status_display_format json;
>          }
>      }
>    ```
> 4. Access to your html.
>    ```
>    http://YOURDOMAIN/status.html
>    ```
> 
> ## To customize before the module installed
> 1. Modify `share/status.template.html` (Do not change `{{uri}}` string)
> 2. Recreate the `ngx_http_vhost_traffic_status_module_html.h` as follows:
>    ```
>    shell> cd util
>    shell> ./tplToDefine.sh status.template.html > ../src/ngx_http_vhost_traffic_status_module_html.h
>    ```
> 3. Add the module to the build configuration by adding
>    `--add-module=/path/to/nginx-module-vts`
> 4. Build the nginx binary.
> 5. Install the nginx binary.
==≠========≠================
Please give an example that explain the customisation process
