### ISSUE TITLE
Json error parser

### ISSUE THREAD

**Issue by vorlon001** [vozlt/nginx-module-vts#131]
Nginx 1.15.0

Uncaught SyntaxError: Unexpected token . in JSON at position 17718
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.b.onload (statuszone:1)
b.onload @ statuszone:1
load (async)
vtsGetData @ statuszone:1

".....[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"requestBuckets":{"msecs":[],"counters":[]},"overCounts":{"maxIntegerSize":18446744073709551615,"requestCounter":0,"inBytes":0,"outBytes":0,"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0,"requestMsecCounter":0}}},"agent::~^(system.*)\.itzone\.online$":{"windows":{"requestCounter":207,"inBytes":107047,"outBytes":4573133,"responses":{"1xx":0,"2xx":196,"3xx":10,"4xx":1,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0},"requestMsecCounter":14,"requestMsec":0,"requestMsecs":{"times":[1530360304054,1530360304067,1530360304067,1530360304068,1530360304071,1530360304077,1530360304081,1530360304096,1530360304097,1530360304098,1530360304099,1530360304100,1530360304102,1530360304107,1530360304109,1530360304113,1530360304114,1530360304119,1530360304120,1530360304128,1530360304128,1530360304128,1530360304129,1530360304130,1530360304130,1530360304141,1530360304142,1530360309173,1530360311758,1530360320779,1530360330168,1530360330196,1530360330204,1530360330213,1530360330227,1530360335481,1530360335510,1530360335518,1530360335525,1530360335526,1530360335541,1530360335545,1530360335557,15303603....."

**Comment by vozlt** [comment]
Thanks for reporting.
What do you use web browser?
Do you get the same error on other web browsers?
Please give me the full part of the json document to check the problem.

**Comment by vorlon001** [comment]
I fix error on nginx 1.15.0 only for vhost "server_name  ~^(system.*)\.itzone\.online$;"
if disable vts from this vhost, error not fix.

**Comment by vozlt** [comment]
I added the function that escape strings for filter's names.
But the ngx_escape_json() function does not handle the `'.'` character.
Anyway, please test with the lastest version below.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/1a01a87e66c9f111fb399cf40def33ab193ae393

**Comment by vorlon001** [comment]
its works.
I will monitoring nginx some time my server.

**Comment by vorlon001** [comment]
its works.

**Comment by dioni21** [comment]
@vozlt Do you intend to release a new tag with this bug fix soon?
