### ISSUE TITLE
Upstream group  is not show data at json  format 

### ISSUE THREAD

**Issue by egg41230** [vozlt/nginx-module-vts#133]
Hello:
I want to get upstream group data for json format on browse, but i can not get  upstream group data .
I used the following command:
http://xxx.xxx/status/control?cmd=status&group=upstream@group&zone=upstream_group@name
result as follow 
,please help me,thx

**Comment by vozlt** [comment]
@egg41230 
See the [manual](https://github.com/vozlt/nginx-module-vts#to-get-group-zones).

#### Examples
```
/control?cmd=status&group=upstream@group&zone=*

/control?cmd=status&group=upstream@group&zone=backend@10.10.10.10:80
```
