### ISSUE TITLE
Reported Caches Capacity Value ?

### ISSUE THREAD

**Issue by centminmod** [vozlt/nginx-module-vts#137]
Hi i am trying to understand what determines the Caches' reported Capacity value ? Mine is reporting quite high at 8388608 TiB if I am reading that correctly ?

I have configured sliced byte-range caching https://www.nginx.com/blog/smart-efficient-byte-range-caching-nginx/ with

```
proxy_cache_path /tmp/mycache keys_zone=mycache:256m;
```

![nginx-sliced-byte-range-caching-01](https://user-images.githubusercontent.com/5899584/44967733-b7448680-af86-11e8-814c-9aa8a3212fee.png)

Nginx configuration

```
nginx -V
nginx version: nginx/1.15.3 (020918-174629)
built by gcc 8.2.1 20180824 (GCC) 
built with OpenSSL 1.1.0 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
```
> configure arguments: --with-ld-opt='-Wl,-E -L/usr/local/zlib-cf/lib -L/opt/boringssl/.openssl/lib -lcrypto -lssl -L/usr/local/lib -lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/zlib-cf/lib:/opt/boringssl/.openssl/lib:/usr/local/lib' --with-cc-opt='-I/opt/boringssl/.openssl/include -I/usr/local/zlib-cf/include -I/usr/local/include -m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong -flto -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wimplicit-fallthrough=0 -fcode-hoisting -Wno-cast-function-type -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --build=020918-174629 --with-compat --with-http_stub_status_module --with-http_secure_link_module --with-http_flv_module --with-http_mp4_module --add-module=../nginx-rtmp-module --add-dynamic-module=../nginx-module-vts --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_slice_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.2 --add-module=../ngx_cache_purge-2.4.2 --add-dynamic-module=../ngx_devel_kit-0.3.0 --add-dynamic-module=../set-misc-nginx-module-0.32 --add-dynamic-module=../echo-nginx-module-0.61 --add-module=../redis2-nginx-module-0.15 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.18 --add-module=../srcache-nginx-module-0.31 --add-dynamic-module=../headers-more-nginx-module-0.33 --with-pcre-jit --with-http_ssl_module --with-http_v2_module

**Comment by vozlt** [comment]
@centminmod 
I fixed it.
Commit: https://github.com/vozlt/nginx-module-vts/commit/549cc4d0d31b8bea5319c8564917875d03f105e1
FYI. [the way to get cahce information in vts module](https://github.com/vozlt/nginx-module-vts/issues/98#issuecomment-397987893)

**Comment by ninetian** [comment]
cache path set 3700g
but it's show 500m

![bug.png](https://i.loli.net/2021/01/27/Oa5P8DNhgnvCzG9.png)

maybe it's same bug

**Comment by vozlt** [comment]
@ninetian 
I have restored it to its original state.(It is ```keys_zone size```.)
I will take a look again.
commit: https://github.com/vozlt/nginx-module-vts/commit/203bc5bf2d9a2cbf30e7b84313011d8a0adea191

**Comment by vozlt** [comment]
@centminmod 
I added additional information about cacheZones.
Commit: 91bdb14
