### ISSUE TITLE
Request time calculation seems wrong

### ISSUE THREAD

**Issue by deafbabe** [vozlt/nginx-module-vts#138]
I am plotting 'nginx_vts_upstream_request_seconds' from reverse proxy.
I have a server with 4 pools in same upstream, all have the same reply times (deviation is almost zero). But if I create one more upstream with one of pools, in graph it immediately goes 2x lower, and since then has all its metrics twice lower than the other one.
If I change or remove second upstream, it doesn't change anything. Maybe restart is required (I am doing reload) but I cant test now.
See attached screenshot, around 12:41 I've added one more upstream with only pool 9000 in it, and reloaded nginx, and pool 9000 immediately drops 2x and stays like that.
![screenshot_46](https://user-images.githubusercontent.com/22785371/45222669-cd6f8100-b2bd-11e8-8e73-01074cfd1c1d.png)

**Comment by susuper** [comment]
Fixed:
https://github.com/vozlt/nginx-module-vts/pull/145

**Comment by vozlt** [comment]
@deafbabe 
I merged it(https://github.com/vozlt/nginx-module-vts/commit/83a889e5309f0399cbea78effa629ae86e3eb13c).
