### ISSUE TITLE
use vhost_traffic_status_dump error

### ISSUE THREAD

**Issue by hezhaoye** [vozlt/nginx-module-vts#140]
I use the v0.1.18 version,and my nginx version is 1.10.2.

 in http section,the config is :
vhost_traffic_status_zone shared:vhost_traffic_status:64m;
vhost_traffic_status_dump logs/vts.db 30s;
vhost_traffic_status_filter_by_host on;
vhost_traffic_status_average_method AMM 60s;

and the server section is:
location /server_status {
	vhost_traffic_status_bypass_limit on;
	vhost_traffic_status_bypass_stats on;
	vhost_traffic_status_display;
	vhost_traffic_status_display_format json;
	allow 127.0.0.1;
	deny all;
}

so when I start the service,I see nginx error log:
2018/10/08 21:51:23 [alert] 21093#0: open() "logs/vts.db" failed (2: No such file or directory)
so I  create the file manually,but it did't work,and print the error same.
why?

**Comment by jamesstout** [comment]
Does the nginx process have write permissions to the log file? Probably needs to be writable by `www-data`
Does it maybe need the full path? e.g. `/var/log/nginx/vts.db`
