### ISSUE TITLE
Collected before with the same name and label values

### ISSUE THREAD

**Issue by wenfei3** [vozlt/nginx-module-vts#147]
Hi,thanks for your exporter,it is very useful!
Recently,I think I have a few problems.
When I started the nginx_exporter,there were few errors:
![wechatimg370](https://user-images.githubusercontent.com/25998180/48685130-b9b29600-ebef-11e8-8ab7-babb46b21873.jpeg)
then I curled `http://localhost/nginx_status/format/json` and I found that there were two servers in the `esadmin` upstream:
```
"esadmin":[{"server":"10.30.46.147:9100","requestCounter":0,"inByt
es":0,"outBytes":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0},"requestMsecCounter":0,"requestMsec":0,"requestMsecs":{"times":[],"msecs":[]},"requestBuckets":{"msecs":[],"counters":[]},"responseMsecCounter":0,"responseMsec":0,"responseMsecs":{"times":[],"msecs":[]},"responseBuckets":{"msecs":[],"counters":[]},"weight":1,"maxFails":1,"failTimeout":10,"backup":false,"down":false,"overCounts":{"maxIntegerSize":18446744073709551615,"requestCounter":0,"inBytes":0,"outBytes":0,"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"requestMsecCounter":0,"responseMsecCounter":0}},{"server":"10.30.46.147:9100","requestCounter":0,"inBytes":0,"outBytes":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0},"requestMsecCounter":0,"requestMsec":0,"requestMsecs":{"times":[],"msecs":[]}
```
but there was only one in my profile:
![image](https://user-images.githubusercontent.com/25998180/48685451-532e7780-ebf1-11e8-89ac-e40ae72f1ea5.png)
So...what's my problem?
Thanks for any reply!

**Comment by vozlt** [comment]
@wenfei3 
Does it still happen in the VTS [latest version](https://github.com/vozlt/nginx-module-vts/commit/549cc4d0d31b8bea5319c8564917875d03f105e1) and Nginx(>1.18.0)?
