### ISSUE TITLE
Adding module failed ./configure: 2: .: Can't open auto/have

### ISSUE THREAD

**Issue by mihalikv** [vozlt/nginx-module-vts#148]
Hello,
I want to add this module to nginx but somehow auto/have can't be found. For installing i am using 

`install_pagespeed.sh`

script from https://ngxpagespeed.com/install. I investigate this script and everything looks fine and i don't know why it won't find auto/have. Do you have some ideas where can be a problem ? 

config command:
`./configure --add-module=/opt/incubator-pagespeed-ngx-latest-stable --add-module=/nginx-module-vts --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-openssl=/tmp/openssl-1.1.0g --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid`

Thank you.

**Comment by z1017371914** [comment]
i met the same problem,do you solve it?

**Comment by huchaorui** [comment]
config文件换行符问题，解决方法参考：https://www.cnblogs.com/lwcode6/p/11647955.html
