### ISSUE TITLE
Some histograms missing

### ISSUE THREAD

**Issue by seanhoughton** [vozlt/nginx-module-vts#168]
I'm using the new prometheus output which is great. However, we've noticed that the `nginx_vts_server_request_duration_seconds` histogram disappears after the container restarts sometimes. When comparing against working instances I've verified that the configs are all identical and the containers are all at the same sha1 so the binary is identical.

The config I'm using is at https://github.com/seanhoughton/nginx-cache/blob/master/nginx.conf

The buckets are configured like this

```
        vhost_traffic_status_histogram_buckets 0.001 0.005 0.01 0.05 0.1 0.5 1 5 10 50 100 500;
```

The configuration is for a caching proxy and I *do* get bucket values for the `nginx_vts_upstream_request_duration_seconds` histogram.

I looked through the code but I didn't see anything obviously wrong. Could this be related to the saved zone data?

**Comment by davemt** [comment]
@seanhoughton did you ever sort this out?

**Comment by vozlt** [comment]
@seanhoughton 
By default, VTS statistics are reset when nginx is restarted.
FYI, The [vhost_traffic_status_dump](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_dump) option allows you to continue your stats even after restart.
