### ISSUE TITLE
Clear statistics without restart nginx

### ISSUE THREAD

**Issue by dmitryskachkov** [vozlt/nginx-module-vts#17]
Hello. I want to get statistics for all domains 1/minute and clear statistics. How can I clean it without restart nginx?

**Comment by vozlt** [comment]
The feature of data reset without restart does not exist at current version.
However, you try to make it (new_data - old_data) in html to data recalculation if you are skilled at html.

**Comment by vozlt** [comment]
The feature has been added now.
It need deeper and many review by peoples because of it changed many routine. :)

https://github.com/vozlt/nginx-module-vts#control

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/e12984d706a485025d35b978a0c08aac9e84a551
