### ISSUE TITLE
Illegal host header

### ISSUE THREAD

**Issue by linuxhub** [vozlt/nginx-module-vts#170]
Illegal host header , invalid host
Prometheus many invalid host metrics tag
Causes too much influxDB SERIES
For example, 
```bash
curl http://127.0.0.1 -H 'Host: www.linuxhub.org'
curl http://127.0.0.1 -H 'Host: test'
curl http://127.0.0.1 -H 'Host: xxx'
```
Record a lot of invalid hosts

![](http://img-linuxhub-cn.oss-cn-shenzhen.aliyuncs.com/other/2019.10.22.nginx-vts-1-1.jpg)
![](http://img-linuxhub-cn.oss-cn-shenzhen.aliyuncs.com/other/2019.10.22.nginx-vts-1-2.jpg)
![](http://img-linuxhub-cn.oss-cn-shenzhen.aliyuncs.com/other/2019.10.22.nginx-vts-3.jpg)

Instead, you can add a `host` filter configuration file to `nginx-vts-exporter`.

**Comment by dkrutsko** [comment]
Yes, I'm struggling with this as well but I'm unable to replicate it using these curl commands. I am seeing random upstreams in my `::nogroups` though.

**Comment by vozlt** [comment]
@linuxhub You probably have the [vhost_traffic_status_filter_by_host](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_by_host) option enabled. Please check it.

@dkrutsko Please let me know the detailed reproducible settings.
