### ISSUE TITLE
nginx1.16.1 VTS Passed Configure but Can not make

### ISSUE THREAD

**Issue by wanghui122725501** [vozlt/nginx-module-vts#178]
ngx_http_vhost_traffic_status_module.c:344:28: error: ‘ngx_http_upstream_state_t’ has no member named ‘response_sec’
                   (state[i].response_sec * 1000 + state[i].response_msec);
                            ^
/opt/soft/nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:344:59: error: ‘ngx_http_upstream_state_t’ has no member named ‘response_msec’
                   (state[i].response_sec * 1000 + state[i].response_msec);
                                                           ^
make[1]: *** [objs/addon/src/ngx_http_vhost_traffic_status_module.o] Error 1
make[1]: Leaving directory `/opt/soft/nginx-1.16.1'
make: *** [build] Error 2

**Comment by dragonfly-net** [comment]
I built successfully it yesterday...
ls -la /home/builder/rpmbuild/RPMS/x86_64/nginx-mod-http-vts-1.16.1-1.el7.x86_64.rpm
-rw-rw-r-- 1 builder builder 143472 Apr 14 16:17 /home/builder/rpmbuild/RPMS/x86_64/nginx-mod-http-vts-1.16.1-1.el7.x86_64.rpm
Centos 7 x86_64, nginx from Epel

**Comment by vozlt** [comment]
@wanghui122725501
Are you still having the same problem?
