### ISSUE TITLE
Can`t get dynamic created upstreams

### ISSUE THREAD

**Issue by babnikzero** [vozlt/nginx-module-vts#18]
Hello. How i can get list and status of upstreams, which has been created by https://github.com/cubicdaiya/ngx_dynamic_upstream ?
P.S. this data stored in the shared memory zone (http://nginx.org/en/docs/http/ngx_http_upstream_module.html#zone).
nginx 1.9.3
Thanks.

**Comment by vozlt** [comment]
I'll check it soon. I'm busy now.

**Comment by babnikzero** [comment]
Hello. This issue is not in your module, ngx_dynamic_upstream update only peer (ngx_http_upstream_rr_peer_t) in  uscf (ngx_http_upstream_srv_conf_t) and did not update servers (ngx_http_upstream_server_t). 
Sorry.

**Comment by vozlt** [comment]
I added support the feature that upstream peers use shared memory.
You can test it in the latest version.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/995c20a6539c3c24ad3f891cfa3590918f19641c

**Comment by babnikzero** [comment]
Hi, sorry for slow feedback.
It seems that everything is working correctly
Thank you
