### ISSUE TITLE
Is there a way to monitor a group of endpoints into single one

### ISSUE THREAD

**Issue by miracleluchen** [vozlt/nginx-module-vts#187]
In my system, there is endpoint like _/api/callback/{txnid}_. 
When I tried to enable VTS, there are quite a lot of path due to the txnid is unique. I am wondering if there is a way that VTS can monitor such endpoints as a single one _/api/callback/_

**Comment by ervinsh** [comment]
@miracleluchen 

I played with this module in the past, and you can consider using **vhost_traffic_status_filter_by_set_key** directive:
https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_by_set_key

It may look something like this:
```
map $request_uri $vts_request_type {
    ~^/api/callback/(.*)$ api_callback;
    default others;
}

server {
    vhost_traffic_status_filter_by_set_key $vts_request_type request_type::$server_name;
}
```
