### ISSUE TITLE
Cache status causes cache lock

### ISSUE THREAD

**Issue by DBezemer** [vozlt/nginx-module-vts#19]
With the new cache status overview (which is awesome) the cache locks are not released and upon restart the following errors occur:

```
2015/08/25 07:29:15 [alert] 5661#5661: ignore long locked inactive cache entry 6c7b231443395c911bbfed66866da923, count:1
```

This appears to be a similar issue to what I found here: https://github.com/FRiCKLE/ngx_slowfs_cache/commit/58000766d900732d0e801f0bcbb96a5f45ad3685 and because of a lock on the increment count the files are not release/flushed.

**Comment by vozlt** [comment]
Thanks for the report.
I will check it soon.

**Comment by vozlt** [comment]
I've added locking routine for `cache->sh->size` variable.
Please check it whether it was a problem.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/47b07ac42c8f9f895774318e7d117bb2dbf88403

**Comment by jessp01** [comment]
Hello,

Could you please issue a new tag with this fix?
Thanks,

**Comment by vozlt** [comment]
Ok, is done with v0.1.2.
Thanks.

https://github.com/vozlt/nginx-module-vts/tree/v0.1.2

**Comment by jessp01** [comment]
@vozlt - thanks very much.
@DBezemer - I release a new package built with VTS v0.1.2 - kaltura-nginx-1.8.0-6
