### ISSUE TITLE
Is there any reason to use nginx-vts-exporter?

### ISSUE THREAD

**Issue by hryamzik** [vozlt/nginx-module-vts#190]
Readme contains link to nginx-vts-exporter while module itself exposes metrics in prometheus format.

Is there any reason to use a standalone exporter?

**Comment by hnlq715** [comment]
Consider prometheus format is well implemented in nginx-module-vts, it is not recommended to use nginx-vts-exporter :-)

And I have decided that [nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter) is not maintained any more.

**Comment by jedi201321** [comment]
hi,  some versions don't have the prometheus-format.
