### ISSUE TITLE
Abonded repository: New official fork?

### ISSUE THREAD

**Issue by Project0** [vozlt/nginx-module-vts#192]
It looks like @vozlt is inactive for over 2 years in github, so i guess there is no maintainer anymore who can merge PRs.
I fear using this module as patches are now spread across different forks, makes it impossible to adopt and maintain that in my company.

I think it would be great to have a new official fork (or even better a github org) to keep changes up in sync.
wdyt?

**Comment by binlab** [comment]
If so, would be nice! Hope @vozlt will agree

**Comment by BlakeB415** [comment]
+1 This is definitely needed.

**Comment by vozlt** [comment]
Sorry. For a long time, I haven't been able to properly manage the source codes on the excuse of being busy.
I have appointed two collaborators.(@SuperQ, @u5surf )
