### ISSUE TITLE
 the value of total connections in Server main and Server zones is wrong

### ISSUE THREAD

**Issue by captaingoodguy** [vozlt/nginx-module-vts#195]
The problem is that the value of total connections in Server main and Server zones of the status webpage is too big, it's wrong, i have checked all of the nginx access logs, there's not so many connections in this one of our systems. after I restart Nginx, the number(Req/s) increase too fast。Pls help

nginx.conf:
```
 location  /status {
           vhost_traffic_status off;
           vhost_traffic_status_display;
           vhost_traffic_status_display_format html;
        #   vhost_traffic_status_bypass_limit on;
        #   vhost_traffic_status_bypass_stats on;
           access_log off;
           allow xx.xx.xx.xx;
           deny all;
        }
```
![image](https://user-images.githubusercontent.com/34262723/101457985-32b8ed80-3971-11eb-8d08-fe4b1072a915.png)

**Comment by captaingoodguy** [comment]
does anyone had this problem?pls help

**Comment by hroost** [comment]
Unfortunately, there is no detailed information for debugging.
Try create simple nginx setup and test it, then if problem still exist - upload `nginx -T` output somewhere and link here.
Also would be useful if you provide commands and methodology of how do you comparing stats and etc.
