### ISSUE TITLE
ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "vhost_traffic_status"

### ISSUE THREAD

**Issue by chenwenjun-github** [vozlt/nginx-module-vts#197]
Anything I can do here?

> 2021/01/22 14:32:32 [error] 14722#14722: *341397 handler::shm_add_server() failed while logging request, client: 10.178.132.1, server: grpc, request: "POST /tensorflow.serving.PredictionService/Predict HTTP/2.0", upstream: "grpc://10.178.226.156:8500", host: "10.200.212.34:30691"

> 2021/01/22 14:51:31 [error] 14722#14722: *341502 shm_add_node::ngx_slab_alloc_locked() failed: used_size[0], used_node[0] while logging request, client: 10.178.132.1, server: grpc, request: "POST /tensorflow.serving.PredictionService/Predict HTTP/2.0", upstream: "grpc://10.178.179.245:8500", host: "10.200.212.34:30691"

> 10.178.132.1 - - [22/Jan/2021:14:51:31 +0000] "POST /tensorflow.serving.PredictionService/Predict HTTP/2.0" 200 156003 492 "-" "grpc-java-netty/1.20.0" "-""10.178.179.245:8500" "200" "0.012" "0.013"

> 2021/01/22` 14:51:31 [crit] 14722#14722: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "vhost_traffic_status"

> 2021/01/22 14:56:31 [crit] 14722#14722: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "vhost_traffic_status"

I have see the same problem in other issue and the advice is to add config like 'vhost_traffic_status_zone shared:vhost_traffic_status:32m;' in /etc/nginx/nginx.conf
but this error occur again, so can you give me some suggest

ps:
I use nginx -s reload to update nginx.conf, need I restart nginx to update the nginx.conf?
And other strange place is "ngx_slab_alloc_locked() failed: used_size[0], used_node[0]", the used_size is 0, I don't know why

**Comment by utszcrystal** [comment]
read the fucking code please
