### ISSUE TITLE
Upstream status dynamic update

### ISSUE THREAD

**Issue by ssabchew** [vozlt/nginx-module-vts#20]
I am using this module: https://github.com/cubicdaiya/ngx_dynamic_upstream/ to manage upstreams, but status is not changed on the status page.
Is it possible to be done?

Regards,
ssabchew

**Comment by vozlt** [comment]
Please check the issue with closed issue https://github.com/vozlt/nginx-module-vts/issues/18.

**Comment by vozlt** [comment]
I will soon support the feature that upstream peers use shared memory.

**Comment by vozlt** [comment]
The work has been completed.
You can test it in the latest version.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/995c20a6539c3c24ad3f891cfa3590918f19641c

**Comment by haobohuiying** [comment]
prometheus display format also need to support to get dynamic upstream peers
