### ISSUE TITLE
Can I use nginx-module-vts on Ubuntu without having to compile Nginx myself?

### ISSUE THREAD

**Issue by seisvelas** [vozlt/nginx-module-vts#202]
For example, the module Headers More can be installed on my distro via the nginx-extras package. Is there a way this module can be acquired and integrated into the way my distro's package manager offers Nginx, or is compiling it in directly the way to go?

Thanks!

**Comment by midorinet** [comment]
you can compile the module as dynamic module, and load it trough load_module in nginx.conf to enable it

**Comment by eilandert** [comment]
I added this module on customer request to my nginx setup. I haven't tested it yet but it should be working.

https://deb.paranoid.nl/nginx-modules/
