### ISSUE TITLE
Whether this module does not support NGINX 1.20.1 ?

### ISSUE THREAD

**Issue by Yuuuuuukit** [vozlt/nginx-module-vts#205]
error happen when ./configure
adding module in /root/nginx-module-vts
./configure: 2: .: Can't open auto/have

**Comment by kingdruid** [comment]
I recently successfully built for nginx 1.20.1 with [build_module.sh](http://hg.nginx.org/pkg-oss/file/stable-1.20/build_module.sh)

**Comment by soulteary** [comment]
I've test it with 1.20 / 1.21, if you use docker or ubuntu/debian, you can use pre-built modules directly.

https://github.com/nginx-with-docker/ngx_http_vhost_traffic_status_module

**Comment by mathieu-aubin** [comment]
i build for 1.20.1 using `add-dynamic-module=...` instead of `add-module=...` with no issues at all.

i believe @Yuuuuuukit you have the wrong path for the module location.

**Comment by aminvakil** [comment]
`--add-module=/path/to/nginx-module-vts` works for me on 1.20.1 too.

**Comment by mathieu-aubin** [comment]
Maybe try using a directory other than /root to make surethe build can access the files...

I vote on closing this issue

**Comment by CSimpiFoN** [comment]
Working properly with 1.20.2.
