### ISSUE TITLE
There is a reflected XSS vulnerability in this module

### ISSUE THREAD

**Issue by nBp1Ng** [vozlt/nginx-module-vts#209]
The location where the vulnerability is triggered is / status / **_xxx_**. When I enter an arbitrary content after the / status /, the program will splice this content into the jsonurl in the front-end page, and the program will not filter JS code. Therefore, XSS attack can be realized by constructing JS code at this location.
![1](https://user-images.githubusercontent.com/33454436/129754135-f465da66-63d0-496e-b68d-513d80557c5d.png)

**Comment by u5surf** [comment]
@nBp1Ng 
Hi, it seems to be same or similar issue #174.
Have you checked the bug fix at the version which include this commit? : https://github.com/vozlt/nginx-module-vts/commit/87d7de91599e4d4452c730dc70d60fd89145bfb7

**Comment by u5surf** [comment]
@nBp1Ng 

Above the commit has included in v0.2.0(latest)
Can you close this issue if you check and satisfy the fix?
https://github.com/vozlt/nginx-module-vts/releases/tag/v0.2.0

**Comment by nBp1Ng** [comment]
> @nBp1Ng Hi, it seems to be same or similar issue #174. Have you checked the bug fix at the version which include this commit? : [87d7de9](https://github.com/vozlt/nginx-module-vts/commit/87d7de91599e4d4452c730dc70d60fd89145bfb7)

yes ,  they are the same , I have closed this issue
