### ISSUE TITLE
Active connections per server

### ISSUE THREAD

**Issue by sergiyshutov** [vozlt/nginx-module-vts#21]
This module have total active connections, and this is cool. But how about active connections per server?

**Comment by vozlt** [comment]
The active connections in nginx-module-vts uses global variables(`ngx_stat_*`) like `src/http/modules/ngx_http_stub_status_module.c` which collects data(accepted, handled, active, requests, reading, writing, waiting) from the outside(`src/{core/,event/}`) of modules.
 Accordingly perhaps, adding the feature in nginx-module-vts looks pretty hard or impossible without modify nginx's main sources(`src/{core/,event/}`).
