### ISSUE TITLE
Possible to show statistics for Nginx TCP streams ?

### ISSUE THREAD

**Issue by centminmod** [vozlt/nginx-module-vts#22]
Is it possible to show Nginx TCP stream stats http://nginx.org/en/docs/stream/ngx_stream_core_module.html

i.e. for TCP load balanced Redis Cluster in Nginx https://community.centminmod.com/posts/18882/

**Comment by vozlt** [comment]
I have a plan to add the feature later(now busy).

**Comment by centminmod** [comment]
sweet much appreciated :+1:

**Comment by gembin** [comment]
+ 1

**Comment by crestone** [comment]
+1

**Comment by aliel** [comment]
+1

**Comment by vozlt** [comment]
I have added a modules of that feature.
I haven't much test yet.
Be careful because segfault may be occur. 😆 

* [nginx-module-sts](https://github.com/vozlt/nginx-module-sts)
* [nginx-module-stream-sts](https://github.com/vozlt/nginx-module-stream-sts)
