### ISSUE TITLE
"Can't locate Test/Nginx/Socket.pm in @INC" when test

### ISSUE THREAD

**Issue by GaoShengXin** [vozlt/nginx-module-vts#220]
Hi
In perl test file under 't/',  it seems like need `Test/Nginx/Socket.pm`:

```
use Test::Nginx::Socket;
```

But I can't find file `Socket.pm` in this project.

Could someone solve this problem? Thanks a lot!

**Comment by u5surf** [comment]
@GaoShengXin 
Hi, It is required the perl library [Test::Nginx::Socket](https://metacpan.org/pod/Test::Nginx::Socket)

It's easy to install it. 
E.g. ubuntu.
```
$ apt install -y cpanminus
$ cpanm install Test::Nginx::Socket

**Comment by GaoShengXin** [comment]
Thanks. It's helpful.
