### ISSUE TITLE
Request for a new version release including the XSS vulnerability fix (for issues/174) made on Jan 24th 2021

### ISSUE THREAD

**Issue by KiranXSingh** [vozlt/nginx-module-vts#225]
Hi,
May I request a new version release for nginx-vts module (perhaps 0.1.19) to include the new modifications made to the code to fix the XSS vulnerability issue (issues/174). Appreciate in advance.
https://github.com/vozlt/nginx-module-vts/issues/174

**Comment by u5surf** [comment]
@KiranXSingh 
This commit has included in v0.2.0
Can you close this issue if you check and satisfy the fix?
https://github.com/vozlt/nginx-module-vts/releases/tag/v0.2.0
