### ISSUE TITLE
Does this work with nginx 1.20.2?

### ISSUE THREAD

**Issue by prabumohan** [vozlt/nginx-module-vts#227]

**Comment by aminvakil** [comment]
Yes.

**Comment by testn** [comment]
Did you have nginx_upstream_check_module?

--add-module=../nginx_upstream_check_module-master

**Comment by prabumohan** [comment]
yes
https://github.com/yaoweibin/nginx_upstream_check_module
For this module when i check health for upstream they report correct whereas Nginx Vhost Traffic Status always saya Up for all upstream servers though they are down 

Is that expected ?

**Comment by testn** [comment]
You probably did not patch https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/check_1.20.1%2B.patch

**Comment by prabumohan** [comment]
i did and hence got the active health check working.. the issue now is for Nginx-module-vts module still flags all upstream servers up in its status page

**Comment by testn** [comment]
Did you configure the check?
https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/README#L14

**Comment by prabumohan** [comment]
yes check is setup... 
![image](https://user-images.githubusercontent.com/14094639/158790072-934d854e-9ea9-4305-a78c-d3a9bbb3c777.png)
as per the screenshot as you can see it reports up but actual its down

**Comment by vozlt** [comment]
@prabumohan 
I've never tested [nginx_upstream_check_module](https://github.com/yaoweibin/nginx_upstream_check_module).(https://github.com/vozlt/nginx-module-vts/pull/134#issuecomment-762902797)
The peer->_check_index_ variable is defined in the [nginx_upstream_check_module](https://github.com/yaoweibin/nginx_upstream_check_module) and it looks like it can be used only by patching it in nginx.
If it continues to be a problem during compilation,, remove it as below!

```patch
--- ngx_http_vhost_traffic_status_display_json.c        2021-01-25 00:21:14.610002559 +0900
+++ ngx_http_vhost_traffic_status_display_json.c.o      2022-09-05 23:43:21.015685286 +0900
@@ -10,10 +10,6 @@
 #include "ngx_http_vhost_traffic_status_display_json.h"
 #include "ngx_http_vhost_traffic_status_display.h"
 
-#if (NGX_HTTP_UPSTREAM_CHECK)
-#include "ngx_http_upstream_check_module.h"
-#endif
-
 
 u_char *
 ngx_http_vhost_traffic_status_display_set_main(ngx_http_request_t *r,
@@ -582,17 +578,7 @@ ngx_http_vhost_traffic_status_display_se
                 usn.max_fails = peer->max_fails;
                 usn.fail_timeout = peer->fail_timeout;
                 usn.backup = 0;
-#if (NGX_HTTP_UPSTREAM_CHECK)
-                if (ngx_http_upstream_check_peer_down(peer->check_index)) {
-                    usn.down = 1;
-
-                } else {
-                    usn.down = 0;
-                }
-#else
                 usn.down = (peer->fails >= peer->max_fails || peer->down);
-#endif
-
 #if nginx_version > 1007001
                 usn.name = peer->name;
 #endif
```

**Comment by u5surf** [comment]
@prabumohan 
Hi, It seems the same issue of this.
https://github.com/vozlt/nginx-module-vts/issues/262#issuecomment-1462348599
We consider that it is quite tricky because it is a little complicated mechanism when the peer->fails is counted on pure nginx upstream. 

So that a lot of people confuse what to do and not to recognize the necessary of the upstream status collect module such as `nginx_upstream_check_module`.

To check the copatiblity of it and this module, we also consider that it should prepare the procedure how to setup with it in this README and the combined test case in this CI before too long.
