### ISSUE TITLE
Wildcard domain support

### ISSUE THREAD

**Issue by Dids** [vozlt/nginx-module-vts#24]
I'm using this module with nginx 1.8, and I plan on having hundreds of different virtualhosts proxied through this nginx installation.

My current setup allows me to use wildcard nginx virtualhosts (ie. I'm specifying "server_name *.domain.com;"), but unfortunately this doesn't seem to work with this nginx module.

As you might've guessed, I'm seeing "*.domain.com" as the zone name in the module's output.

Is there a way to overwrite this, so I could, say, use "$host" instead of server_name as the zone name?

**Comment by vozlt** [comment]
Your thinking is as follows:

```Nginx
server {
  server_name *.domain.com
  .
  .
}
```
1. nginx's server_name is as above
2. and clients requested to server with hostname such as (a|b|c).domain.com or *.domain.com 
3. then vts modules's output is as follows:
```

zone                Requests ...
a.domain.com ...
b.domain.com ...
c.domain.com ...
.
.
.
```
As above, what I understand, nginx-module-vts's zone names are the same as requested hostname like $host variable.
Is that right?

**Comment by Dids** [comment]
Yes, exactly! But right now, the vts module is only showing "*.domain.com" as the only server zone.

**Comment by vozlt** [comment]
OK, Thanks for the idea.
That feature does not existing in module now but I will try to add the feature which separates by host header soon. :)

**Comment by vozlt** [comment]
It added the `vhost_traffic_status_filter_by_host` directive in v0.1.3 tag.
It need deeper and many review by peoples.

latest commit: https://github.com/vozlt/nginx-module-vts/commit/4ace1346066526efcc274ad4c0d5fe0c11be8c1e

**Comment by Dids** [comment]
Thank you for this, however, so far I've been unable to get the ```vhost_traffic_status_filter_by_set_key``` directive working.

Here's how I'm setting it up:
```
server
{
        ...

        if ($host ~* (.*)\.my-domain\.com)
        {
            set $subdomain $1;
            vhost_traffic_status_filter_by_set_key $subdomain;
        }
        else
        {
            vhost_traffic_status_filter_by_set_key $host;
        }

        ...
}
```

**Comment by Dids** [comment]
It works fine when I set it at the beginning of a server block, but not inside the if sentence. I'm guessing that's just the way nginx behaves?

Here's the error:
```
nginx: [emerg] "vhost_traffic_status_filter_by_set_key" directive is not allowed here
```

**Comment by vozlt** [comment]
You're right. The directives `vhost_traffic_status_filter_by_host` and `vhost_traffic_status_filter_by_set_key` is allowed only at the server, location context as of now.
I would consider later.

FYI. The `vhost_traffic_status_filter_by_set_key` directive will be soon changed to add large numbers of zones. e.g. You will see country traffic aside from server zones if you are used geoip module.

**Comment by vozlt** [comment]
The `vhost_traffic_status_filter_by_host` directive is able to set in `http` directive from now on at v0.1.4.
You try it.
Last version: https://github.com/vozlt/nginx-module-vts/tree/v0.1.4
