### ISSUE TITLE
server zones bug  

### ISSUE THREAD

**Issue by hailiangchen** [vozlt/nginx-module-vts#263]
I configured tow sites, both using localhost, but with different ports.

Problem:
You cannot distinguish two sites in the server zones list.
![image](https://user-images.githubusercontent.com/12914054/222621598-7594f5bc-d437-4a09-a707-d2dff3598353.png)

**Comment by u5surf** [comment]
@hailiangchen Thanks reporting. We tend to investigate deeply such the behavior, can you let us your nginx(if you have third party fork such as openresty, tengine and so on) version and configuration.

**Comment by hailiangchen** [comment]
Tengine version: Tengine/2.3.3
nginx version: nginx/1.18.0

**Comment by u5surf** [comment]
@hailiangchen 
You mean you'd like to serve the different port and get their metrics separately.
How about using `vhost_traffic_status_filter_by_set_key` like this?

```
http {
    include       mime.types;
    default_type  application/octet-stream;

    #vhost_traffic_status_zone shared:vhost_traffic_status:32m;
    vhost_traffic_status_zone;
    upstream backend {
            server localhost:8080;
    }

    vhost_traffic_status_filter_by_set_key $server_port server::ports::$server_addr;
    server {
        listen 8081;
        location /backend {
            proxy_pass http://backend;
        }
        location /status {
            check_status;
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;

            access_log off;
        }
    }
    server {
        listen 8082;
        location /backend {
            proxy_pass http://backend;
        }
    }
    server {
        listen 8083;
        location /backend {
            proxy_pass http://backend;
        }
    }
```
<img width="1039" alt="スクリーンショット 2023-04-10 22 07 40" src="https://user-images.githubusercontent.com/14180225/230907559-b5390414-6755-460c-829c-c804a4aed4bc.png">

**Comment by hailiangchen** [comment]
ok, i'll try
