### ISSUE TITLE
broken nginx 1.9.7 support ?

### ISSUE THREAD

**Issue by centminmod** [vozlt/nginx-module-vts#27]
@vozlt did latest [Nov 20th commits](https://github.com/vozlt/nginx-module-vts/commits/master) break nginx 1.9.7 support https://community.centminmod.com/posts/20624/ ? As it compiled fine prior to those commits

    make -f objs/Makefile install
    make[1]: Entering directory `/svr-setup/nginx-1.9.7'
    ccache /usr/bin/clang -ferror-limit=0 -c -I/usr/local/include/luajit-2.1  -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g -m64 -mtune=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion  -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_pagespeed-1.9.32.10-beta/psol/include -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/chromium/src -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/google-sparsehash/src -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/protobuf/src -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/re2/src -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/out/Release/obj/gen -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/apr/src/include -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/aprutil/src/include -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I ../ngx_pagespeed-1.9.32.10-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I ../ngx_devel_kit-0.2.19/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.1 -I ../lua-nginx-module-0.9.18/src/api -I ../nginx_upstream_check_module-0.3    .0 -I ../pcre-8.37 -I ../libressl-2.2.4/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.2.19/src -I src/mail -I src/stream \
            -o objs/addon/src/ngx_http_vhost_traffic_status_module.o \
            ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:904:22: error: adding 'unsigned int' to a string does not append to the string [-Werror,-Wstring-plus-int]
        len = ngx_strlen(ngx_vhost_traffic_status_group_to_string(type));
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:341:30: note: expanded from macro 'ngx_vhost_traffic_status_group_to_string'
        : "NO\0UA\0UG\0CC\0FG\0" + 3 * n                                           \
                                 ^
    src/core/ngx_string.h:61:51: note: expanded from macro 'ngx_strlen'
    #define ngx_strlen(s)       strlen((const char *) s)
                                                      ^
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:904:22: note: use array indexing to silence this warning
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:341:30: note: expanded from macro 'ngx_vhost_traffic_status_group_to_string'
        : "NO\0UA\0UG\0CC\0FG\0" + 3 * n                                           \
                                 ^
    src/core/ngx_string.h:61:51: note: expanded from macro 'ngx_strlen'
    #define ngx_strlen(s)       strlen((const char *) s)
                                                      ^
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:915:23: error: adding 'unsigned int' to a string does not append to the string [-Werror,-Wstring-plus-int]
        p = ngx_cpymem(p, ngx_vhost_traffic_status_group_to_string(type), len);
            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:341:30: note: expanded from macro 'ngx_vhost_traffic_status_group_to_string'
        : "NO\0UA\0UG\0CC\0FG\0" + 3 * n                                           \
                                 ^
    src/core/ngx_string.h:103:60: note: expanded from macro 'ngx_cpymem'
    #define ngx_cpymem(dst, src, n)   (((u_char *) memcpy(dst, src, n)) + (n))
                                                               ^
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:915:23: note: use array indexing to silence this warning
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:341:30: note: expanded from macro 'ngx_vhost_traffic_status_group_to_string'
        : "NO\0UA\0UG\0CC\0FG\0" + 3 * n                                           \
                                 ^
    src/core/ngx_string.h:103:60: note: expanded from macro 'ngx_cpymem'
    #define ngx_cpymem(dst, src, n)   (((u_char *) memcpy(dst, src, n)) + (n))
                                                               ^
    2 errors generated.
    make[1]: *** [objs/addon/src/ngx_http_vhost_traffic_status_module.o] Error 1
    make[1]: Leaving directory `/svr-setup/nginx-1.9.7'
    make: *** [install] Error 2

ah it might be due to using clang compiler and ` adding 'unsigned int' to a string does not append to the string [-Werror,-Wstring-plus-int]` ?

**Comment by centminmod** [comment]
looks like it's due to these 2 instances of errors when using clang compiler instead of gcc compiler

    error: adding 'unsigned int' to a string does not append to the string [-Werror,-Wstring-plus-int]

i managed to work around it by passing `-Wno-string-plus-int` to nginx configure options

nginx -V
nginx version: nginx/1.9.7
built by clang 3.4.2 (tags/RELEASE_34/dot2-final)
built with LibreSSL 2.2.4
TLS SNI support enabled
configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-string-plus-int -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream --with-stream_ssl_module --with-http_gzip_static_module --add-module=../ngx_pagespeed-1.9.32.10-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module --with-http_geoip_module --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-ngx-fancyindex --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../lua-nginx-module-0.9.18 --add-module=../lua-upstream-nginx-module-0.04 --add-module=../lua-upstream-cache-nginx-module-0.1.1 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.28 --with-pcre=../pcre-8.37 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.2.4

**Comment by vozlt** [comment]
Thanks for the report.
I fixed it.
Please check it.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/d6b04f9e299073b6f67851ac9a2301d6fded87b8

**Comment by centminmod** [comment]
yup was fixed but a new one has occurred

    ccache /usr/bin/clang -ferror-limit=0 -c -I/usr/local/include/luajit-2.1  -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g -m32 -mtune=generic -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-string-plus-int -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion -march=i686 -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/chromium/src -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/google-sparsehash/src -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/ia32/include -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/protobuf/src -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/re2/src -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/out/Release/obj/gen -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/out/Release/obj/gen/protoc_out/instaweb -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/apr/src/include -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/aprutil/src/include -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/apr/gen/arch/linux/ia32/include -I ../ngx_pagespeed-release-1.9.32.10-beta/psol/include/third_party/aprutil/gen/arch/linux/ia32/include -I ../ngx_devel_kit-0.2.19/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.1 -I ../lua-nginx-module-0.9.18/src/api -I ../nginx_upstream_check_module-0.3.0 -I ../pcre-8.37 -I ../libressl-2.2.4/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.2.19/src -I src/mail -I src/stream \
                -o objs/addon/src/ngx_http_vhost_traffic_status_module.o \
                ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:2511:38: error: comparison of integers of different signs: 'unsigned int' and 'ngx_int_t' (aka 'int') [-Werror,-Wsign-compare]
        if (vtsn->stat_upstream.type == control->group) {
            ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
    ../nginx-module-vts/src/ngx_http_vhost_traffic_status_module.c:2725:38: error: comparison of integers of different signs: 'unsigned int' and 'ngx_int_t' (aka 'int') [-Werror,-Wsign-compare]
        if (vtsn->stat_upstream.type == control->group) {
            ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
    2 errors generated.
    make[1]: *** [objs/addon/src/ngx_http_vhost_traffic_status_module.o] Error 1
    make[1]: Leaving directory `/svr-setup/nginx-1.9.7'
    make: *** [install] Error 2

**Comment by vozlt** [comment]
I fixed it.
What is the above test version(os version, clang version)?
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/7284e7104b1efee82a5a0510f5ad75f8ff0e87a8

**Comment by centminmod** [comment]
thanks it was same version as above

nginx -V
nginx version: nginx/1.9.7
built by clang 3.4.2 (tags/RELEASE_34/dot2-final)
built with LibreSSL 2.2.4
TLS SNI support enabled
configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-string-plus-int -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream --with-stream_ssl_module --with-http_gzip_static_module --add-module=../ngx_pagespeed-1.9.32.10-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module --with-http_geoip_module --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-ngx-fancyindex --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../lua-nginx-module-0.9.18 --add-module=../lua-upstream-nginx-module-0.04 --add-module=../lua-upstream-cache-nginx-module-0.1.1 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.28 --with-pcre=../pcre-8.37 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.2.4

just my script auto recompiles Nginx and always gets the latest nginx-module-vts code each time, so on an nginx recompile it got your latest commits :)
