### ISSUE TITLE
Can't use control functionality if location has more than a segment

### ISSUE THREAD

**Issue by karbon15** [vozlt/nginx-module-vts#28]
I'm using this module with nginx 1.8, and made the update to version VTS v0.1.6 to benefit from the stats reset functionality.

I was surprised that calling any urls with /my/location/status/control?args would simply return the HTML page without executing the command.

I tried again with a vanilla config, and it seems the module doesn't support control if the location scope containing "vhost_traffic_status_display" is composed of multiple segments.

This configuration will work without a problem: 

```
location /status {
     vhost_traffic_status_display;
     vhost_traffic_status_display_format html;
}
```

while calling http://127.0.0.1/status/control?cmd=reset&group=server&zone=_

If configuring the location with a composed path
```

location /a/segment/structure/status {
     vhost_traffic_status_display;
     vhost_traffic_status_display_format html;
}
```
http://127.0.0.1/a/segment/structure/status/control?cmd=reset&group=server&zone=_

Will return the HTML page.

Anything I'm doing wrong?

**Comment by vozlt** [comment]
Thank you for looking into this
I fixed it right now.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/f7c192a88e206fe4068202364473b07d984a3a4a

**Comment by karbon15** [comment]
Your fix did it for me.  Many thanks!
