### ISSUE TITLE
Question - time window of statistics

### ISSUE THREAD

**Issue by RubenFelix** [vozlt/nginx-module-vts#284]
Hi,

First of all, congratilations for the excelent work.

This is not an issue, just a question about the statistics provided by this module.
While revieweing the information provided by the /status page, I was wondering what is the time window of those statistics? 24h?

I was not able to see this information anywhere.

Thank you!

**Comment by u5surf** [comment]
@RubenFelix 
The statistics time window starts fundamentally from the nginx process started.
You can reset the statistics with this control API.
https://github.com/vozlt/nginx-module-vts?tab=readme-ov-file#to-reset-traffic-zones-on-the-fly
