### ISSUE TITLE
Reset counters after getting status, in one request

### ISSUE THREAD

**Issue by ekini** [vozlt/nginx-module-vts#29]
First of all, thank you for this great plugin!

It'd be nice to have one more feature, though.
I want to periodically request status and reset counters after every one.
Currently, it can be done only in two requests:

    /status/control?cmd=status...
    /status/control?cmd=reset...

But some numbers will be certainly between them.
One more argument to cmd=status would save the situation, for example:

    /status/control?cmd=status&reset=true
or

    /status/control?cmd=pop # means "pop numbers and clear"

I've tried to do it on my own, but my knowledge of C is very limited.

**Comment by vozlt** [comment]
Sorry, but there is no plan to do so.
Alternatively, I am considering to provide **`nginx-module-lua-vts`** to control without the http request when I get time.
I don't know for sure when that will be.

**Comment by MKhlystun** [comment]
Hi guys. I implemented this issues and send pull request.

**Comment by vozlt** [comment]
Sorry, but as mentioned above, I will not accept that your pull request because I do not want to bother about the mixed web queries.
