### ISSUE TITLE
the status  HTML does not display

### ISSUE THREAD

**Issue by TSLIU2022** [vozlt/nginx-module-vts#295]
When I visit the URL, I do not see any dashboard. the ui as blow! 

<img width="631" alt="image" src="https://github.com/vozlt/nginx-module-vts/assets/91188525/cbb1346f-c166-47a1-b21b-1961ec4fb013">

**Comment by u5surf** [comment]
@TSLIU2022 Hi, could you tell us the detail of your configurations of nginx, module version, and nginx version? We don’t have any clue which can inspect this behavior.
