### ISSUE TITLE
Cant disable server zones by host

### ISSUE THREAD

**Issue by mdpuma** [vozlt/nginx-module-vts#31]
Hi,

How i can disable server zones statistics by server_name/$host ?

vhost_traffic_status_filter off;
vhost_traffic_status_filter_by_host off;

This directives doesn't make any changes on status page.

**Comment by vozlt** [comment]
Basically, the traffic measurement key has at least one per `server{}`.
The default traffic measurement key is a `server_name`.
It takes the very left one when it has mutiple domains.
The `vhost_traffic_status_filter_by_host` is off by default.
The `server{}` config has the high priority than the `http{}` config.
So it overwrites the `http{}` config if you set both `http{}` and `server{}`.
If you want to use the keys by host header field, it does not need to use the `vhost_traffic_status_filter_by_set_key`, just use `vhost_traffic_status_filter_by_host`.

Examples:

```Nginx
server {
  server_name *.example.org;

  ...

}
```
server zones key: `*.example.org`



```Nginx
server {
  server_name *.example.org;
  vhost_traffic_status_filter_by_host on;

  ...

}
```
server zones key: `a.example.org`, `b.example.org`, `~~~.example.org`, ...


```Nginx
http {
vhost_traffic_status_filter_by_host on;

...

server {
  server_name *.example.org;
  vhost_traffic_status_filter_by_host off;

  ...

}
```
server zones key: `*.example.org`

**Comment by mdpuma** [comment]
I tried this configuration

    http {
        vhost_traffic_status_zone;
        vhost_traffic_status_filter_by_host off;
        server {
            server_name website.com;
            vhost_traffic_status_filter_by_host off;
        }   
    }

But i anyway see status page (Server zones) with all of vhosts which i have.

**Comment by vozlt** [comment]
Do you want to except for the specified server in server zones?
If you want to except for the specified `server{}` then you can use the `vhost_traffic_status off`.
As follows:
```Nginx
http {
    vhost_traffic_status_zone;
    server {
        server_name website.com;
        vhost_traffic_status off;
    }   
}
```

**Comment by mdpuma** [comment]
Ok, but now i cant see statistics by filter on disabled server {}

**Comment by vozlt** [comment]
In server zones, either $server_name or $host is essential.
So It is not possible to disable both $server_name and $host.
In other words, a zone($server_name or $host) of server zones can not be replaced with `vhost_traffic_status_filter_by_set_key`.

FYI.
Basically, the zone of server zones has at least one per `server{}` regardless of the `vhost_traffic_status_filter_by_set_key` directive, if `vhost_traffic_status` directive is enabled.
It is either the $server_name or the $host by `vhost_traffic_status_filter_by_host`.
Then later, the filter feature works and added in server zones or filter zones.
The `vhost_traffic_status_filter_by_set_key` directive has nothing to do with server zones, if it uses the two arguments in `vhost_traffic_status_filter_by_set_key` directive. (If it has a one argument, then it go to server zones.)
