### ISSUE TITLE
Connections show

### ISSUE THREAD

**Issue by diluga** [vozlt/nginx-module-vts#32]
i use  openresty/1.9.7.2 with nginx-module-vts,when i used cosbench (mode=s3)to test  HTTP request(with 6000 workers),if my active|reading|writing|waiting  num is > 12000,the nums  are not correct when my test finished（in fact requests is 0，but it still show a big Numbers like 600x） ,please check and fix it！thx！

**Comment by vozlt** [comment]
The Server main(active|reading|writing|waiting|accepted|handled|requests) in nginx-module-vts uses global variables(ngx_stat_*) like src/http/modules/ngx_http_stub_status_module.c which collects data(accepted, handled, active, requests, reading, writing, waiting) from the outside(src/{core/,event/}) of modules.
In other words, nginx-module-vts just uses without calculating the above values(active|reading...) 
For that reason, I wonder whether the values are same or not compared to [ngx_http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html) at that point. Please let me know the status of [ngx_http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html) and nginx-module-vts(format/json) at that point.
