### ISSUE TITLE
Wrong cacheZones maxSize calculation

### ISSUE THREAD

**Issue by peyoh** [vozlt/nginx-module-vts#34]
Hello,
I've seen some inconsistent data in cacheZones:

Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/centos_r620-root   70G  1.7G   69G   3% /
devtmpfs                       48G     0   48G   0% /dev
tmpfs                          48G     0   48G   0% /dev/shm
tmpfs                          48G  137M   47G   1% /run
tmpfs                          48G     0   48G   0% /sys/fs/cgroup
tmpfs                          48G  155M   47G   1% /cache

"my_zone" Cache directory is /cache. 

"cacheZones":{"my_zone":{"maxSize":9223372036854771712,"usedSize":161124352,"inBytes":2191759,"outBytes":1966063488,"responses":

maxSize is really good to be true:). The issue is also in the web page. Maybe tmpfs is a problem?

I'm using master.

BRS

**Comment by vozlt** [comment]
Hi.
The `maxSize` is not a disk size if you have not a defined `max_size` variable in `proxy_cache_path`.
It will be set to `NGX_MAX_OFF_T_VALUE` variable when loading [ngx_http_proxy_module](http://nginx.org/en/docs/http/ngx_http_proxy_module.html).
The variable is defined in `objs/ngx_auto_config.h` which is created in by `./configure`.

`$vi src/http/ngx_http_file_cache.c`
```C
2168 char *
2169 ngx_http_file_cache_set_slot(ngx_conf_t *cf, ngx_command_t *cmd, void *conf)
2170 {
.
.
2204     max_size = NGX_MAX_OFF_T_VALUE;
.
.
2316         if (ngx_strncmp(value[i].data, "max_size=", 9) == 0) {
.
2321             max_size = ngx_parse_offset(&s);
.
2329         }
.
.
2445     cache->max_size = max_size;
```

**Comment by peyoh** [comment]
Thank you!
