### ISSUE TITLE
Possible to calculate CCU (Concurrent User) in each vHost?

### ISSUE THREAD

**Issue by kietnlt** [vozlt/nginx-module-vts#36]
Dear,
Is it possible to calculate CCU (concurrent user ) in each vHost using Nginx Modules VTS ?

Thanks for your help,
My sincere,
Tuan Kiet,

**Comment by vozlt** [comment]
Hi.
Please see the [issues/21](https://github.com/vozlt/nginx-module-vts/issues/21#issuecomment-145789555).

**Comment by kietnlt** [comment]
Thanks so much for your help.
But I think the variable "Total Active Connection" is not CCU because it means how many sessions user interacting with web server. For example, If one user opens two sessions concurrently, the " Total active connection" is 2 but CCU is only 1, i think that.
If there have any mistaken in my options, would you like to give me the favors ?

**Comment by vozlt** [comment]
You're right.
Do you maybe want to count the number of unique IP addresses per second?
The above feature has not been implemented.

**Comment by kietnlt** [comment]
Hi,
Thanks for your help. The module you write is very interesting. It helps me so much in my project to monitor Nginx server.

Best regards,
Tuan Kiet.

**Comment by vozlt** [comment]
Yes, probably I think so if the keepalive is disabled(`keepalive_timeout 0`).
The variable `ngx_stat_active`(active) increased only one per a tcp connection and decreased when a tcp connection is closed.
FYI, See the [ngx_http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html) and [status variables in issue/35](https://github.com/vozlt/nginx-module-vts/issues/35#issuecomment-197157603).
