### ISSUE TITLE
Can show IP or hostname of Server at Status page ?

### ISSUE THREAD

**Issue by hoangh2** [vozlt/nginx-module-vts#37]
Hi

How can i show IP or hostname of server at status page ? Because i have many nginx server, i need to difference its.

Thanks,

**Comment by vozlt** [comment]
Hi.
Please see the [customizing status page](https://github.com/vozlt/nginx-module-vts#customizing).

**Comment by hoangh2** [comment]
Hi Vozlt,

I only need show ip or hostname of server on status page, for example:
Nginx Vhost Traffic Status => Nginx Vhost Traffic Status Server1/192.168.x.x

Can i customize like that ?

Thanks.

**Comment by hoangh2** [comment]
Hi,

I mean It will auto get hostname or ip of server to show up.

Regards,

**Comment by vozlt** [comment]
That feature has not been implemented.

**Comment by vozlt** [comment]
I added hostname feature.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/5f18695f2f1e1c5cfcedeb1ea3d82f6501ea0b3e
