### ISSUE TITLE
Ignore hits to the status page itself

### ISSUE THREAD

**Issue by jebabcock** [vozlt/nginx-module-vts#38]
Is there a quick or direct command to ignore the calls made to the status page itself?

**Comment by vozlt** [comment]
That feature has not been implemented.

**Comment by vozlt** [comment]
I have updated that features.

1. added vhost_traffic_status_bypass_stats directive.
2. added vhost_traffic_status_bypass_limit directive.

It is able to do like the following:

```Nginx
http {
    vhost_traffic_status_zone;

    ...

    server {

        ...

        location /status {
            vhost_traffic_status_bypass_limit;
            vhost_traffic_status_bypass_stats;
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }
    }
}
```

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/9ba24a28aa4a5bf8ebe0c5e77756a5a0fc0a3845

**Comment by TrurlMcByte** [comment]
```invalid number of arguments in "vhost_traffic_status_bypass_limit" directive```
Must be ```vhost_traffic_status_bypass_limit off;```?
And in this case need to update README.md examples

**Comment by vozlt** [comment]
OK, Thanks.
