### ISSUE TITLE
Clustered Stats

### ISSUE THREAD

**Issue by jebabcock** [vozlt/nginx-module-vts#39]
Is there a way or plans to support aggregating the results from multiple nginx instances? IE, one instance collects results via json from other additional nginx instances in addition to its own and provides a full aggregated results page.

On a side note, This tool is pretty awesome.

**Comment by vozlt** [comment]
Thanks for good suggestion.
I guess It could be using the 3rd party tools such as html(with javascript), python, perl, etc.
I’ll think about it.

**Comment by nottix** [comment]
In our company we are using this module with our 10 nginx instances and it's working very well, thank you @vozlt.
I think that aggregated results should be very usefull to complete the solution, any plan to add it? Or do you know of a third party solution that we can use?

Thank you.

**Comment by vozlt** [comment]
Hi, I had forgotten about it because I was so busy. :)

1. any plan to add it
=> I haven't made any plans yet. (I'll think about it when I get time.)

2. third party solution
=> I have not found any yet. (I'm just not looking hard enough.)

**Comment by nottix** [comment]
thank you @vozlt .
