### ISSUE TITLE
possible traffic limit?

### ISSUE THREAD

**Issue by tatsuo-ike** [vozlt/nginx-module-vts#40]
호스팅 환경에서 아파치 시절의 mod_throttle이나 mod_cband의 대용으로 사용할 수 있을지 고려중입니다.
bandwidth는 기타 모듈들로 제어가 가능한데, transfer를 기준으로 제어하는 모듈은 현재까지 없어 보입니다.
혹시 transfer limit의 기능에 대해서 개발 계획이 있으신지 궁금합니다.

좋은 모듈 개발해 주셔서 감사합니다.

**Comment by vozlt** [comment]
이미 전체 전송량 제어 기능은 구현(`vhost_traffic_status_limit_traffic`) 되어 있습니다.
아래 참고 하시면 됩니다.

https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_limit_traffic
https://github.com/vozlt/nginx-module-vts#limit
