### ISSUE TITLE
vhost_traffic_status_limit_traffic_by_set_key size does not accept variables?

### ISSUE THREAD

**Issue by mbejda** [vozlt/nginx-module-vts#41]
Hello, 
I'm getting odd behavior when passing in the `size` parameter when its a variable. The variable does not render. Is this normal? 

```
set $member request;
set $traffic 100;
  vhost_traffic_status_limit_traffic_by_set_key FG@storage::$server_name@$subdomain $member:$traffic 402;
```

**Comment by vozlt** [comment]
Yes, It is.
The size variable using in `vhost_traffic_status_limit_traffic` directive must be a integer number or size type(k|m|g).
