### ISSUE TITLE
beonpush hiden code

### ISSUE THREAD

**Issue by bits16** [vozlt/nginx-module-vts#42]
Hi, I noticed very strange piece, I made proxying of statistics of NGINX, and made a mistake, instead of status, prescribed status2, and the module to me gave the 404th error message from the website beonpush.com
I apply the Screenshot http://screenshot.ru/1796de63e158f7cf66458bf4fd79d0ae
at you in a code this address is hidden?

**Comment by vozlt** [comment]
I am not exactly sure what you are asking, but there is no hardcoded status or status2 in the source code, so there should be no difference.

Please try to access without rewrite or status only server{}  or other port as follows:
```nginx
http {
    vhost_traffic_status_zone;

    ...

    server {

        server_name status.example.com;

        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }
    }
}
```

```nginx
http {
    vhost_traffic_status_zone;

    ...

    server {
        listen 1981;
        server_name status.example.com;

        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }
    }
}
```

FYI. It will work as long as the strings match regardless of length.
`/status` == `/statusabc` == `/status1` == `/status...`

**Comment by bits16** [comment]
The matter is that if this website isn't available, then monitoring of hosts as from this website js and css files judging by the log of the server are loaded isn't loaded

**Comment by vozlt** [comment]
I am sorry that the explanation is so convoluted for me.
Please explain to me one more time as follows:

1. nginx configuration
2. requests
3. responses
4. logs
