### ISSUE TITLE
Response time on server or filter zones?

### ISSUE THREAD

**Issue by bobthemighty** [vozlt/nginx-module-vts#43]
It would be incredibly useful if I could monitor the response time of server zones.

I'm happy to open a pull request, if you can tell me where I should start looking.

**Comment by vozlt** [comment]
Thanks for good suggestion.
I have a plan to add the feature later.

**Comment by vozlt** [comment]
I added that feature just now.
Please test...
Latest commit: https://github.com/vozlt/nginx-module-vts/commit/60aad47e06e079ee7074247aaabad08748c9b3cc

**Comment by bobthemighty** [comment]
That's great news. I have a [collectd plugin](https://github.com/bobthemighty/collectd-vts) that I wrote for vts, so I'll update it and test this out. Thanks a lot :)
