### ISSUE TITLE
Incorrect Upstream/Server/State

### ISSUE THREAD

**Issue by zarmack** [vozlt/nginx-module-vts#44]
Hi,

I've got configured a upstream with two servers

upstream BENJS {
  server 127.0.0.1:53000;
  server 127.0.0.1:53001;
}

On 127.0.0.1:53001 the service is stopped, but on VTS's status page, the state is "up".

It's a mistake ?

Best Regards,
Zarmack

**Comment by vozlt** [comment]
Hi, It is normal.

The state is not currently state.
The state(down field in json) is just value(down) in upstream group.
So, the state is static field by upstream config.
See the ngx_http_upstream_module docs.
http://nginx.org/en/docs/http/ngx_http_upstream_module.html#down

**Comment by zarmack** [comment]
Many thanks !
