### ISSUE TITLE
VTS segfault when balancer_by_lua breaks

### ISSUE THREAD

**Issue by moshisushi** [vozlt/nginx-module-vts#45]
Maybe a bit of a weird corner case but could be worth handling:

When playing around with balancer_by_lua_block in (nginx/OpenResty) and "vhost_traffic_status_zone" set, I noticed that workers would segfault when there are errors in the lua code. While this is not something that should usually happen, it highlights the fact that there are cases where ngx_http_upstream_state_t.peer is NULL, which is not handled in VTS (looking at other parts of the nginx source, it seems like they always NULL-check that variable before use).

This change adds handling for that:
https://github.com/moshisushi/nginx-module-vts/commit/592a13d00cefefa0c4028243703048330cbe3c56

Error log without fix:
`2016/07/13 10:56:12 [error] 11293#11293: *1 failed to run balancer_by_lua*: balancer_by_lua:8: attempt to call global 'foo' (a nil value)
stack traceback:
        balancer_by_lua:8: in function <balancer_by_lua:1> while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2016/07/13 10:56:12 [alert] 11291#11291: worker process 11293 exited on signal 11`

Error log with fix:
`2016/07/13 10:53:55 [error] 11239#11239: *1 failed to run balancer_by_lua*: balancer_by_lua:8: attempt to call global 'foo' (a nil value)
stack traceback:
        balancer_by_lua:8: in function <balancer_by_lua:1> while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2016/07/13 10:53:55 [error] 11239#11239: *1 handler::shm_add_upstream() failed while logging request, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"`

**Comment by vozlt** [comment]
Thanks for the report.
I will check it soon.

**Comment by vozlt** [comment]
Thanks.
The nginx-module-vts has been updated as suggested.(https://github.com/vozlt/nginx-module-vts/commit/96f84affb768637ef4f388184acc0cc168d44036).
Please test.

**Comment by moshisushi** [comment]
Thanks, looks good!

`2016/07/18 08:50:27 [error] 21813#21813: *1 failed to run balancer_by_lua*: balancer_by_lua:2: attempt to call global 'f' (a nil value)
stack traceback:
	balancer_by_lua:2: in function <balancer_by_lua:1> while connecting to upstream, client: 127.0.0.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2016/07/18 08:50:27 [error] 21813#21813: *1 shm_add_upstream::peer failed while logging request, client: 127.0.0.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2016/07/18 08:50:27 [error] 21813#21813: *1 handler::shm_add_upstream() failed while logging request, client: 127.0.0.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"`
