### ISSUE TITLE
Error building on i686

### ISSUE THREAD

**Issue by non7top** [vozlt/nginx-module-vts#47]
```ngx_http_vhost_traffic_status_module.c:3587: error: integer constant is too large for 'long' type```
https://build.opensuse.org/build/home:non7top/CentOS_CentOS-6/i586/nginx/_log

**Comment by vozlt** [comment]
Hi, Thanks for reporting.
The above link redirects to https://build.opensuse.org with message( `anonymous_user(Anonymous user is not allowed here - please login):`).
Maybe you are using centos6/i686/gcc, Please give me the building system information to be sure.(os, compiler,  nginx-module-vts version)

**Comment by non7top** [comment]
Thank you for your time. Here is the same log file. OS is indeed centos6/i686/gcc.
[_log.zip](https://github.com/vozlt/nginx-module-vts/files/380642/_log.zip)

**Comment by vozlt** [comment]
Thanks.
The nginx-module-vts has been updated as suggested.(https://github.com/vozlt/nginx-module-vts/commit/89cfcd908c22ad44501757eb575fc0df29d250d6).
Please test.

**Comment by non7top** [comment]
Thank you! It builds fine now on i686.
