### ISSUE TITLE
make pull(push)time (refresh) configurable

### ISSUE THREAD

**Issue by itpp16** [vozlt/nginx-module-vts#5]
Can you make the refresh time configurable? 1 - 5 seconds, mostly a refresh every 3 seconds is enough.
vhost_traffic_status_display_refresh 3

Maybe add configuration options for colors?
ea. 
when value is higher then xx change text colors.
vhost_traffic_status_display_trigger_connections_waiting 1000 white on red
vhost_traffic_status_display_trigger_responses_5xx 500 white on red
(click on white text on red background to reset counter and color)
vhost_traffic_status_display_upstream_down white on red

**Comment by vozlt** [comment]
If you want to change interval, then you need only to modify vtsUpdateInterval and vtsStatusURI variables in share/status.template.html and then just load it.
My original purpose was to separate data and html so I have been separated accessing as format/json and format/html.
For that reason, Built-in html was lightly on purpose.
You can be modified or create a new html pretty good(e.g. graph) than built-in html.
If no one do that, I would do it when have time.
I don't know for sure when that will be. :)

**Comment by itpp16** [comment]
Aha! I missed that :) looks good enough to change that externally.
