### ISSUE TITLE
Upstreams not showing as down

### ISSUE THREAD

**Issue by 112madgamer** [vozlt/nginx-module-vts#53]
Hello everybody I just set this up and doing some testing i turned one of my upstream serves off and spammed the Load Balancing with requests from "ab" but it seems to show that it is up.

server 1 is 192.xxx.1.14:80 up 17ms
server 2 is 192.xxx.1.15:80 up 3.4s

but server 2 is turned off and there is no fallback setup yet

my config is round robin is that a problem?

please help

**Comment by vozlt** [comment]
Hi, the state(up|down) is just mark value in upstream group.
See the issue https://github.com/vozlt/nginx-module-vts/issues/44.
