### ISSUE TITLE
Add average response time per interval

### ISSUE THREAD

**Issue by nedmax** [vozlt/nginx-module-vts#57]
It would really nice to have a sliding window with the average (max, min also?) response time to users.
There is a lot of people doing this today through access log or other modules, like nginx-statsd, which seems to me very expensive.

**Comment by vozlt** [comment]
Thanks for good suggestion.
There are many similar requests like https://github.com/vozlt/nginx-module-vts/issues/43.
I have a plan to add the feature later but I'm a little tied up now.

**Comment by nedmax** [comment]
Ok @vozlt, no problem. Thanks.
We could close this one and keep with #43. Choose what works best for you.

**Comment by pavelnemirovsky** [comment]
IMHO there is a good approach implemented here https://github.com/yandex-sysmon/nginx-lua-stats

**Comment by vozlt** [comment]
I added that feature just now.
Please test...
Latest commit: https://github.com/vozlt/nginx-module-vts/commit/60aad47e06e079ee7074247aaabad08748c9b3cc

**Comment by linbo** [comment]
@vozlt I check the code, looks it will average processing time for  last 64 requests, right?

**Comment by vozlt** [comment]
By default, It use the 63(NGX_HTTP_VHOST_TRAFFIC_STATUS_DEFAULT_QUEUE_LEN - 1) of recent values to compute but It can be smaller than 63 by the period parameter in [vhost_traffic_status_average_method](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_average_method).
It is a static buffer size.
So If you want to change it, you must change the below file.

`$ vi src/ngx_http_vhost_traffic_status_node.h`
```C
  9 
 10 #define NGX_HTTP_VHOST_TRAFFIC_STATUS_DEFAULT_QUEUE_LEN  ...
 11 
```

Please see the directive [vhost_traffic_status_average_method](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_average_method) if you want to change the average formula.

**Comment by linbo** [comment]
@vozlt Thanks for the help.
