### ISSUE TITLE
add prometheus display format

### ISSUE THREAD

**Issue by andrewsmedina** [vozlt/nginx-module-vts#58]
Prometheus (prometheus.io) is a very powerfull open-source monitoring solution. Prometheus get the data scraping metrics from the applications.

To use prometheus with `nginx-module-vts` is a good way to monitoring and aggregate metrics from more than one `nginx` servers.

A way to do it is the `nginx-module-vts` support `prometheus` as a display format.

**Comment by vozlt** [comment]
Hi, Thanks for your suggestion.
I'll get it checked soon.

**Comment by vozlt** [comment]
Hi, the prometheus exporter for nginx-module-vts has been released by `hnlq715` in issue https://github.com/vozlt/nginx-module-vts/issues/62.
Try to [nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter).

The screenshot `nginx_server_connections` as follows:
![nginx-vts-exporter](https://cloud.githubusercontent.com/assets/3648408/21039515/c495dd5a-be21-11e6-8e6f-488dc2c0cd60.png)

**Comment by gianrubio** [comment]
@vozlt I'm already using nginx-vts-exporter to collect prometheus metrics. It's really easy to use.
My question is why not merge the nginx-vts-exporter with this project and have prometheus metrics by default?

**Comment by vozlt** [comment]
@gianrubio Thanks for your good suggestion.
I have never used prometheus but I installed it because of this issue.
So I don't know detail about it yet.
But I think that it is better to make it a 3rd-party module like [nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter) outside nginx-module-vts to do not affect nginx performance.

**Comment by gianrubio** [comment]
@vozlt prometheus could be an another format for the stats. It'll be a new endpoint like status/format/prometheus. The kubernetes project are using your module for the nginx ingress controller. I'm really interested to make the prometheus format easy to use for everyone. 

It'll be similar to this screenshot. 

![screen shot 2016-12-21 at 15 21 42](https://cloud.githubusercontent.com/assets/5694860/21392746/a781e8ac-c791-11e6-9453-f8731a59db3c.png)

https://github.com/kubernetes/ingress/issues/72

@hnlq715 what do you think?

**Comment by hnlq715** [comment]
The requested feature may break the internal design in [vozlt/nginx-module-vts](https://github.com/vozlt/nginx-module-vts). In my oppinion, it's more wise to start a new project for nginx-prometheus-metrics, or use [hnlq715/nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter) instead.

**Comment by gianrubio** [comment]
@hnlq715, could you explain why this will break the design?

**Comment by pavelnemirovsky** [comment]
Guys did u merge this PR to master?

**Comment by trnl** [comment]
Guys, I also agree that it will not break any designs in nginx-module-vts. Prometheus is just another output similar to existing json, jsonp and html and rendering of it will be a no brainer.

**Comment by hnlq715** [comment]
@gianrubio sorry to reply your question so lately...

Prometheus in vts should use the histogram instead of gauge type for time metrics, not like [hnlq715/nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter), which means a huge change for vts.

Another choice here would be [hnlq715/nginx-prometheus-metrics](https://github.com/hnlq715/nginx-prometheus-metrics), which use lua embedded in nginx.

**Comment by trnl** [comment]
@hnlq715, I agree that this will be a change for vts, however, I believe histograms are not mandatory for now and simple nginx-vts-exporter style gauge output will be fine. I believe that was an original suggestion by @gianrubio.

**Comment by hnlq715** [comment]
@trnl @vozlt @gianrubio 
I agree, without supporting histogram type, this change would be acceptable.

But it would be great to support histogram for time metrics, and we could achieve this with lua or c module. After all, we could have p90, p95 or p99 request/response time metrics...

**Comment by hnlq715** [comment]
Hope this could help you guys, simple lua code generates nginx's prometheus metrics.
https://github.com/hnlq715/nginx-prometheus-metrics

**Comment by trnl** [comment]
@hnlq715, actually yes. We rely on that now. However it will be nice to have the same stuff in nginx-ingress-controller for Kubernetes.

**Comment by nri-pl** [comment]
#114

**Comment by vozlt** [comment]
That feature has added.
All mertric names are started with nginx_vts_(*).
I can not guarantee that it will work well because I know little about prometheus.
Please test it.
Thanks.

Latest commit: 2f9434f

**Comment by hadret** [comment]
Overall `format/prometheus` appears to work very well. I haven't test the histogram buckets yet, but I noticed some other things missing when it comes to the `upstreams` part:

- State of the backend is not provided
- Weight of the backend is not provided
- MaxFails of the backend is not provided
- FailTimeout of the backend is not provided

All of the above are very useful to have and are provided by other formats.
