### ISSUE TITLE
Req/s and Traffic in JSON status

### ISSUE THREAD

**Issue by qarizma** [vozlt/nginx-module-vts#60]
It seems that I can't find some stats in the JSON output. Reading the JSON output seems not to have the requests/s value, and no Sent/s Rcvd/s traffic values.

The HTML page is working fine. Am I doing something wrong? Any advice what I can do to troubleshoot this?

Thanks

**Comment by vozlt** [comment]
Hi, It is calculated as follows in html and the 1 second ago `requestCounter` value is there in html(javascript variables).

Req/s = (current `requestCounter` - 1 second ago `requestCounter`)

**Comment by tamer1009** [comment]
Thanks. But requestCounter is always 0 in the JSON output...

**Comment by qarizma** [comment]
Thanks, but both requestCounter is always 0 in JSON output...

**Comment by vozlt** [comment]
I have some questions to confirm it.

1. Does it happen on all systems?
2. What nginx and nginx-module-vts version are you using?
3. I would like to see the html screenshot and json content if you can.

**Comment by qarizma** [comment]
I'm using nginx 1.11.6 and the latest vts plugin.

![html](https://cloud.githubusercontent.com/assets/8611981/20757153/825863d0-b715-11e6-9f51-ba59ff5bf6be.png)

`{"nginxVersion":"1.11.6","loadMsec":1480517137266,"nowMsec":1480517615429,"connections":{"active":2,"reading":0,"writing":1,"waiting":1,"accepted":230,"handled":230,"requests":674},"serverZones":{"website.com":{"requestCounter":209,"inBytes":16715,"outBytes":1936387,"responses":{"1xx":0,"2xx":186,"3xx":22,"4xx":1,"5xx":0,"miss":16,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":15,"scarce":0},"overCounts":{"maxIntegerSize":18446744073709551615,"requestCounter":0,"inBytes":0,"outBytes":0,"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0}},"_":{"requestCounter":464,"inBytes":180406,"outBytes":3962956,"responses":{"1xx":0,"2xx":459,"3xx":0,"4xx":5,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0},"overCounts":{"maxIntegerSize":18446744073709551615,"requestCounter":0,"inBytes":0,"outBytes":0,"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0}},"*":{"requestCounter":673,"inBytes":197121,"outBytes":5899343,"responses":{"1xx":0,"2xx":645,"3xx":22,"4xx":6,"5xx":0,"miss":16,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":15,"scarce":0},"overCounts":{"maxIntegerSize":18446744073709551615,"requestCounter":0,"inBytes":0,"outBytes":0,"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0}}},"upstreamZones":{"::nogroups":[{"server":"X:80","requestCounter":194,"inBytes":13636,"outBytes":1931662,"responses":{"1xx":0,"2xx":186,"3xx":7,"4xx":1,"5xx":0},"responseMsec":19,"weight":0,"maxFails":0,"failTimeout":0,"backup":false,"down":false,"overCounts":{"maxIntegerSize":18446744073709551615,"requestCounter":0,"inBytes":0,"outBytes":0,"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0}}]},"cacheZones":{"cache":{"maxSize":1073741824,"usedSize":741376,"inBytes":3673,"outBytes":496099,"responses":{"miss":16,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":15,"scarce":0},"overCounts":{"maxIntegerSize":18446744073709551615,"inBytes":0,"outBytes":0,"miss":0,"bypass":0,"expired":0,"stale":0,"updating":0,"revalidated":0,"hit":0,"scarce":0}}}}`

It seems to be working now...not sure why. Is there a way to calculate Req/s from the JSON output? Or do I have to save the requestCounter in a variable and call it again?

If I'm correctly, the inBytes and outBytes are the CURRENT incoming and outgoing bytes?

Thanks

**Comment by vozlt** [comment]
Or do I have to save the requestCounter in a variable and call it again?
=> Yes, you have to save the `requestCounter` in a variable.

If I'm correctly, the inBytes and outBytes are the CURRENT incoming and outgoing bytes? Or is it the traffic used?
=> It is a cumulative number like `requestCounter`. It is also the same calculation method.

Thanks.

**Comment by qarizma** [comment]
Thanks you, it makes sense now. Closing this 👍
