### ISSUE TITLE
Change "Total traffic" label for "all" in JSON

### ISSUE THREAD

**Issue by welitonfreitas** [vozlt/nginx-module-vts#61]
In some applications that make parse of the result in Json use "*" as wildcard. Total traffic could be "all".

**Comment by vozlt** [comment]
Thanks.
I will consider it.

**Comment by vozlt** [comment]
The above feature is added.
The directive is the [vhost_traffic_status_display_sum_key](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_display_sum_key).
For example: `vhost_traffic_status_display_sum_key` all
I haven't much test yet.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/c24820c6c44425cb717eeb6875b5bf5a8c37e49c
