### ISSUE TITLE
Please add support sending metric to graphite feature

### ISSUE THREAD

**Issue by jindov** [vozlt/nginx-module-vts#65]
Thank you for this awesome module, vozlt!
This is really what I need to monitor my infras, really cool. Can u consider to add a feature that it can send all metrics to graphite. Thanks

**Comment by vozlt** [comment]
Hi, Thanks for your good suggestion.
I have not enough time to look at it(`Prometheus`, `Graphite`) because of so busy just now.
I'll do that when I get time.

FYI. The prometheus exporter for nginx-module-vts has been released by hnlq715 in issue #62.
