### ISSUE TITLE
Read metric variable of module inside config of Nginx

### ISSUE THREAD

**Issue by crestone** [vozlt/nginx-module-vts#66]
Is there now a possibility to read the variables of the module and use them in a config of Nginx?
I need this for transmit a connection counter from an application url to backend server as "proxy_set_header"
As on example:
```
 http {
    upstream backend {
        server srv1.example.com;
        server srv2.example.com;
        server srv3.example.com;
    }

    server {
        listen 80;

        location /app1 {
            proxy_pass http://backend;
            
            vhost_traffic_status_filter_by_host on;
            vhost_traffic_status_filter_by_set_key app:1 ID;
            
            proxy_set_header VTS-Connection-Metric $vhost_traffic_status_read_connection_current;
        }
    }
}
```
May be need do some patch or something else?
Thanks!

**Comment by vozlt** [comment]
Hi, I don't know exactly what you want but `nginx-module-vts` has already embedded variables.
See the https://github.com/vozlt/nginx-module-vts#variables.

See the following link for connection variables(active,reading,writing,waiting).
https://nginx.org/en/docs/http/ngx_http_stub_status_module.html#variables.

FYI. [Issue/21: Active connections per server](https://github.com/vozlt/nginx-module-vts/issues/21)

**Comment by crestone** [comment]
Thanks for answer!
I need to count the number of client requests received in current context e.g.:
```
server {
    listen 80;

    location /app1 {
        proxy_pass http://backend;
        
        vhost_traffic_status_filter_by_host on;
        vhost_traffic_status_filter_by_set_key app:1 ID;
    }
    
    location /app2 {
        proxy_pass http://backend;
        
        vhost_traffic_status_filter_by_host on;
        vhost_traffic_status_filter_by_set_key app:2 ID;
    }
    
    location /app3 {
        proxy_pass http://backend;
        
        vhost_traffic_status_filter_by_host on;
        vhost_traffic_status_filter_by_set_key app:3 ID;
    }
}
```
I need a separated cont for each path of url:
http://example.com/app1
http://example.com/app2
http://example.com/app3
etc

**Comment by vozlt** [comment]
OK, what you want is to get a value set by `vhost_traffic_status_filter_by_set_key` and make it a variable. For example, You might want to get current requestCounter of "`vhost_traffic_status_filter_by_set_key app:1 ID;`".
Is right?

**Comment by crestone** [comment]
Yes, you are right! I need possibility to read variable for "vhost_traffic_status_filter_by_set_key app:1 ID;", "vhost_traffic_status_filter_by_set_key app:2 ID;" etc

**Comment by vozlt** [comment]
That feature does not exist at now but I will consider it soon.
Thanks for your suggestion.

**Comment by crestone** [comment]
Thanks so much for your work! Hope you can add this functionality soon

**Comment by vozlt** [comment]
I added that feature as mentioned above.
I haven't much test yet. 😆
In the above case,  you are able to do like the following:
```Nginx
server {

...

    location /app1 {
        vhost_traffic_status_filter_by_set_key app:1 ID;
        vhost_traffic_status_set_by_filter $requestCounter filter/ID@app:1/requestCounter;
        proxy_set_header VTS-Connection-Metric $requestCounter;

        ...

    }
}
```

Please see the following links:

https://github.com/vozlt/nginx-module-vts#set
https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_set_by_filter

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/631f60e607bf58736ed2bae844c83baa76faaba9
