### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by devangn** [vozlt/nginx-module-vts#70]
I have compiled nginx with --add-module=/path/to/nginx-module-vts
now when i add 'vhost_traffic_status_zone' under 'http' part in nginx.conf and restart nginx i am getting below note and nginx is staring in (exited) mode.
Starting nginx: nginx: [emerg] unknown directive "vhost_traffic_status_zone" in /etc/nginx/nginx.conf:11

How to resolve this 'unknown directive' issue?

**Comment by devangn** [comment]
with, /etc/init.d/nginx reload everything works
/etc/init.d/nginx restart through unknown directive "vhost_traffic_status_zone"

**Comment by vozlt** [comment]
Hi, try like belows:

1. Compile lastest commit: https://github.com/vozlt/nginx-module-vts/commit/701e32987c2d1a56868941df2ecb23bd793e8da9

2. Configuration & start
```Nginx
http {
    vhost_traffic_status_zone;
    ...
    server {
    ...
}
```

3. Check if the nginx-module-vts symbols are exist using `nm` command. 

`$ nm -n /home/devel/install/nginx/sbin/nginx.devel | grep vhost_traffic_status`

```Bash
00000000004cf82d t ngx_http_vhost_traffic_status_zone
00000000004cfa67 t ngx_http_vhost_traffic_status_init_zone
.
.
.
```
