### ISSUE TITLE
segfault on nginx-1.11.10

### ISSUE THREAD

**Issue by sukaslayer** [vozlt/nginx-module-vts#71]
CentOS 6.8 x86_64
nginx + nginx-module-vts built with rpmbuild (spec here: https://clbin.com/RDZ65)

example config:

server {
  listen       *:8081;
    server_name            localhost;
  location / {
     root /var/www;
    }
}

curl -v  http://127.0.0.1:8081/
* About to connect() to 127.0.0.1 port 8081 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 127.0.0.1:8081
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
* Closing connection #0

tail   /var/log/nginx/error.log 
2017/03/07 12:59:15 [alert] 683923#683923: worker process 684118 exited on signal 11 (core dumped)
2017/03/07 12:59:15 [alert] 683923#683923: worker process 684167 exited on signal 11 (core dumped)
2017/03/07 13:02:23 [alert] 683923#683923: worker process 684173 exited on signal 11 (core dumped)

gdb BT:

(gdb) bt
#0  ngx_http_vhost_traffic_status_set_by_filter_variables (r=0x7f437b350da0) at /tmp/nginx-module-vts/src/ngx_http_vhost_traffic_status_set.c:410
#1  ngx_http_vhost_traffic_status_set_handler (r=0x7f437b350da0) at /tmp/nginx-module-vts/src/ngx_http_vhost_traffic_status_set.c:40
#2  0x00007f4379e72b03 in ngx_http_core_access_phase (r=<value optimized out>, ph=0x7f437b3692b8) at src/http/ngx_http_core_module.c:1084
#3  0x00007f4379e6fc2d in ngx_http_core_run_phases (r=0x7f437b350da0) at src/http/ngx_http_core_module.c:860
#4  0x00007f4379e7b15c in ngx_http_process_request (r=0x7f437b350da0) at src/http/ngx_http_request.c:1916
#5  0x00007f4379e7be68 in ngx_http_process_request_line (rev=0x7f437b36fd60) at src/http/ngx_http_request.c:1028
#6  0x00007f4379e63f83 in ngx_epoll_process_events (cycle=<value optimized out>, timer=<value optimized out>, flags=<value optimized out>) at src/event/modules/ngx_epoll_module.c:902
#7  0x00007f4379e5a3bf in ngx_process_events_and_timers (cycle=0x7f437b340e30) at src/event/ngx_event.c:242
#8  0x00007f4379e61a38 in ngx_worker_process_cycle (cycle=0x7f437b340e30, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:753
#9  0x00007f4379e60029 in ngx_spawn_process (cycle=0x7f437b340e30, proc=0x7f4379e619d0 <ngx_worker_process_cycle>, data=0x0, name=0x7f4379f0071a "worker process", respawn=0)
    at src/os/unix/ngx_process.c:198
#10 0x00007f4379e62984 in ngx_reap_children (cycle=0x7f437b340e30) at src/os/unix/ngx_process_cycle.c:621
#11 ngx_master_process_cycle (cycle=0x7f437b340e30) at src/os/unix/ngx_process_cycle.c:174
#12 0x00007f4379e3c46c in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:368

**Comment by vozlt** [comment]
Thanks for the report.
I fixed it just now and re-tagged to v0.1.13.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/701e32987c2d1a56868941df2ecb23bd793e8da9

**Comment by sukaslayer** [comment]
thanks, checked, working now
