### ISSUE TITLE
How to count response times separate by respose time ranges?

### ISSUE THREAD

**Issue by weldpua2008** [vozlt/nginx-module-vts#73]
Hello,
I have a huge traffic > 10000 rqs so I need to count a number of requests per second that had the following response time 0-100msec, 100-250msec, 250-500msec, more then 500 msec 

I found that https://github.com/vozlt/nginx-module-vts/blob/c24820c6c44425cb717eeb6875b5bf5a8c37e49c/src/ngx_http_vhost_traffic_status_node.h#L20 length of array is 63 element. So I can't calculate it from a json.

Also I have impression that requestMsec (average of request processing times in milliseconds) is not working on my traffic.

Please advise.

**Comment by vozlt** [comment]
### Increasing the length of array in request_times.

By default, It use the 63 of recent values to compute.
It is a static buffer size.
So If you want to change it, you must change the below file and complie.
Also it will need to be set enough shared memory.
I will add the shared memory information in JSON soon. 


`$ vi src/ngx_http_vhost_traffic_status_node.h`
```C
 10 
 11 #define NGX_HTTP_VHOST_TRAFFIC_STATUS_DEFAULT_QUEUE_LEN  ...
 12 
```

### The formula of requestMsec
The default formula is the [WMA](https://en.wikipedia.org/wiki/Moving_average#Weighted_moving_average)(Weighted moving average).
I will add [AMM](https://en.wikipedia.org/wiki/Arithmetic_mean)(Arithmetic mean) formula and add directive to choice the formulas soon.
I think that the [AMM](https://en.wikipedia.org/wiki/Arithmetic_mean) seems like better than [WMA](https://en.wikipedia.org/wiki/Moving_average#Weighted_moving_average) if req/s is too huge.

Please see the related issue https://github.com/vozlt/nginx-module-vts/pull/67

**Comment by vozlt** [comment]
![vts-shared-memory](https://cloud.githubusercontent.com/assets/3648408/23784739/0e637bbe-05a7-11e7-9073-eec5f0ba430f.png)

I have updated that features.
1. added shared memory sections.
2. added `vhost_traffic_status_average_method` directive.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/80a1a5da32380ad59412a178b1378c221a15edea

**Comment by pznamensky** [comment]
Hello,
We faced with the same issue.
Sure, best choice is to get percentile of a response time. But I suppose that it is possible to get only average percentile. Unfortunately usually we need to get percentile at the specific time range.
Nevertheless it would be great if it'll be possible to define some time ranges inside the server block in the nginx config and than to get requests count which refer to the time range.
This could make possible to get request time statistic and than to graph it based on pre-defined time ranges.
Is it possible to implement such feature?

**Comment by vozlt** [comment]
Please see the [requestMsecs](https://github.com/vozlt/nginx-module-vts#json-used-by-status) field in JSON to get the requestMsec per time. You can calculate the average response time by a specified time range if you manually use requestMsecs.
```Json
.
.
"requestMsecs":{
  "times":[1493344496983,1493344497034,1493344497042,...],
  "msecs":[0,0,100,...]
}
.
.
```
* requestMsecs
  * times
    * The times in milliseconds at request processing times.
  * msecs
    * The request processing times in milliseconds.

Please see the *period* parameter of [vhost_traffic_status_average_method](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_average_method) to specify the time range to calculate the average response time. The *period* parameter is an effective time of the values(requestMsecs -> msecs) used for the average calculation.

**Comment by pznamensky** [comment]
Thanks for your reply.
You are saying about average response time, but average time usually doesn't represent real situation.
For instance, sometimes we have some very long requests, which is usual for us, but average response time increases dramatically.
Pre-defined time ranges with request counters are not flexible but sometimes it is more convenient to add them into monitoring tools.
And yes. We could calculate percentiles according requestMsecs field if we'll increase queue length.
But we can't set this big queue length size only for specific site. And often percentiles calculation based on values from requestMsecs field this is not so convenient as getting simple request count.
If you are thinking that pre-defined time-ranges with counters is not the best choice then is it possible to add ability to set queue length in more flexible way?

**Comment by linbo** [comment]
@pznamensky  I prefer to analyze log for this case.

**Comment by vozlt** [comment]
@pznamensky 
There is no plan for setting queue length dynamically yet.
Instead, I am considering the accumulated requestMsec that proposed by @linbo at [pull/67](https://github.com/vozlt/nginx-module-vts/pull/67#issuecomment-299815026).
Let me think about it a little bit.

**Comment by pznamensky** [comment]
@vozlt 
What do you think about adding buckets with upper time limit?
That's the way mtail provides statistics: https://github.com/google/mtail/blob/master/docs/Programming-Guide.md#histograms
Histograms could help to calculate Apdex score or percentiles for sertain bucket.

**Comment by SuperQ** [comment]
Even something as simple as showing the total request time as a counter would improve this.  Rather than trying to internally calculate the average, exposing a counter would allow external monitoring like Prometheus to provide a more accurate averaging.

But adding [Prometheus-style](https://prometheus.io/docs/practices/histograms/) histograms would be extremely useful.

**Comment by vozlt** [comment]
I added the cumulative request time fields as `requestMsecCount`, `responseMsecCount` in JSON.

From now on the average formula for request processing time is available by users as follows:
*`average_request_msec` = `(current_request_msec_counter - last_request_msec_counter) / (current_request_counter - last_request_counter)`*

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/deb2aedc9308f4aeb5d3656d1a709877b618d3e6
