### ISSUE TITLE
compatibility issue with ngx_upstream_resolveMK

### ISSUE THREAD

**Issue by TrurlMcByte** [vozlt/nginx-module-vts#75]
compatibility issue with https://github.com/HatsuneMiku3939/ngx_upstream_resolveMK
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055eaa7a5f8f6 in ngx_http_vhost_traffic_status_display_set_upstream_group ()
```
on vhost_traffic_status_display

**Comment by vozlt** [comment]
Thanks for the report.
I fixed it to prevent segfault but to be compatible with the nginx-module-vts module, the corresponding source also needs to be modified as follows:
```Diff
diff --git a/ngx_http_upstream_resolveMK.c b/ngx_http_upstream_resolveMK.c
index 41c210a..637bf0a 100644
--- a/ngx_http_upstream_resolveMK.c
+++ b/ngx_http_upstream_resolveMK.c
@@ -295,6 +295,9 @@ static char *ngx_http_upstream_resolveMK(ngx_conf_t *cf, ngx_command_t *cmd,
        domain.data = value[1].data;
        domain.len  = value[1].len;
 
+       us->addrs = ngx_pcalloc(cf->pool, sizeof(ngx_addr_t));
+       us->addrs->name = domain;
+
        if (ngx_strncmp(value[2].data, "service=", 8) != 0) {
                ngx_conf_log_error(NGX_LOG_EMERG, cf, 0,
                                   "service is not given");
```

If you do not as the above, you will not see it in status page in nginx-module-vts.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/17caacab3821f1a562947637043969c7f1a90087

**Comment by TrurlMcByte** [comment]
Great! In my fork with specific changes for SkyDNS it's working fine.

**Comment by TrurlMcByte** [comment]
not show any real info about dynamic upstream, but I'm collecting this data directly
Idea: add Prometheus compatible "/metrics" page for collected data

**Comment by vozlt** [comment]
If upstream real ip is not show in nginx-module-vts, try as follows:
```
...
local /backend {
    vhost_traffic_status_filter_by_set_key $upstream_addr backend;
    proxy_pass backend;
}
```
If `$upstream_addr` variable exists, will show in filterZones and the above patch is not required.

Please see the https://github.com/vozlt/nginx-module-vts/issues/68#issuecomment-279402291

**Comment by TrurlMcByte** [comment]
result like:
```
Zone
192.168.1.11:9002
192.168.1.11:0, 192.168.1.11:0
```
looks like also see wrong tries also, not a problem

**Comment by vozlt** [comment]
You'd better ask the module developer if the module works well.
