### ISSUE TITLE
Compilation issue regarding ‘not_supported’ label

### ISSUE THREAD

**Issue by uschaufelberger** [vozlt/nginx-module-vts#77]
My setup:
* Distro: Ubuntu 14.04
* Compiler: Tried both gcc 4.4 and 4.8
* Nginx: 1.10.3
* Compile time options:       --with-openssl=openssl-1.0.2k \
      --with-file-aio \
      --with-ipv6 \
      --with-http_ssl_module \
      --with-http_realip_module \
      --without-http_access_module \
      --without-http_auth_basic_module \
      --without-http_autoindex_module \
      --without-http_geo_module \
      --without-http_map_module \
      --without-http_split_clients_module \
      --without-http_referer_module \
      --without-mail_pop3_module \
      --without-mail_imap_module \
      --without-mail_smtp_module \
      --without-http_scgi_module \
      --without-http_uwsgi_module \
      --without-http_fastcgi_module \
      --without-http_memcached_module \
      --without-http_limit_conn_module \
      --without-http_limit_req_module \
      --without-http_upstream_hash_module \
      --without-http_upstream_ip_hash_module \
      --without-http_upstream_least_conn_module \
      --without-http_upstream_zone_module \
      --error-log-path=/dev/null \
      --pid-path=/var/run/nginx.pid \
      --http-client-body-temp-path=$(CARGO_TEMP)/nginx/body-temp \
      --http-proxy-temp-path=$(CARGO_TEMP)/nginx/proxy-temp \
      --conf-path=/opt/cargo/etc/nginx/nginx.conf \
      --http-fastcgi-temp-path=$(CARGO_TEMP)/nginx/fastcgi-temp \
      --add-module=../nginx-upload-module \
      --add-module=../masterzen-nginx-upload-progress-module-cfbbbf8 \
      --add-module=../headers-more-nginx-module-0.32 \
      --add-module=../mod_zip-ca0b345bc156902df9a5187cc7ea2452256189cf \
      --add-module=../nginx-module-vts ;\

Trying to compile the current master branch, I get the following error:
../nginx-module-vts/src/ngx_http_vhost_traffic_status_display.c: In function ‘ngx_http_vhost_traffic_status_display_get_upstream_nelts’:
../nginx-module-vts/src/ngx_http_vhost_traffic_status_display.c:473:1: error: label ‘not_supported’ defined but not used [-Werror=unused-label]

I can get it to compile by moving the label 'not_supported:' into the "#if (NGX_HTTP_UPSTREAM_ZONE)" block, but that seems a bit of a hack..

**Comment by uschaufelberger** [comment]
Oh, I just realized this was caused by excluding http_upstream_zone_module, which seems to be required...

**Comment by vozlt** [comment]
Thanks for reporting the error.
You are not wrong.
I fixed it.

latest commit: https://github.com/vozlt/nginx-module-vts/commit/9725ede7c707be459abcb90412d837e31bc6d5e5
