### ISSUE TITLE
restore status

### ISSUE THREAD

**Issue by hemith** [vozlt/nginx-module-vts#78]
좋은 모듈 정말 감사드립니다.

서버를 리부팅하면 vts 정보가 유지 되지 않는데,

리부팅 후에도 이전 상태가 유지되게 할 수 있을까요? 

만약에 가능하지 않다면 해당 기능을 지원해 주실 수는 없을까요?

Thank you for a nice module!

Traffic status is deleted after server rebooting.

Is it possible to restore status?

**Comment by vozlt** [comment]
현재 해당 기능은 존재하지 않습니다.
시계열 데이터베이스를 이용하면 해당 기능이 그다지 필요성이 없어 보여서 고려하지 않고 있는데 혹시 어떤 부분에서 필요하신지요?
비슷한 이슈(https://github.com/vozlt/nginx-module-vts/issues/50)가 있었습니다.

**Comment by hemith** [comment]
각 사이트 마다 **기간 별로 이용 가능한 트래픽량**을 정하려 하는데
서버 리부팅 후에 ?cmd=status 의 outBytes 정보가 초기화 되어서 
리부팅 전까지 이용된 각 사이트의 트래픽 정보를 놓치는 것이 문제였습니다.

내용 파악에 도움이 될까 싶어서 참고로 몇 가지 정보를 나열합니다.
- nginx.conf 설정은 사이트 별로 server {} 를 설정하지 않고 1개의 server {} 로 구성되었습니다.
- 접속되는 도메인은 계속해서 늘어나며 서버 1대에 1만개 수준을 예상하고 있습니다.
- 하나의 사이트는 여러 개의 도메인으로 연결되며 이 경우 해당 사이트의 트래픽은 ?cmd=status 를 읽어서 합산 처리하도록 구현 했습니다. 
- 각 사이트 마다 정해진 트래픽을 초과하면 nginx 외에 다른 영역에서 접근을 제어합니다.
- vts 의 각 zone 마다 정해진 이용 기간을 주기로 ?cmd=reset 합니다.

그리고,
apache v1.x 의 mod_throttle 모듈과
apache v2.x 의 mod_cband 모듈의 경우에는
트래픽 이용량이 서버 리부팅 후에도 유지가 되어서 이러한 경우를 고려하지 않았었습니다.
nginx vts 모듈이 반드시 위의 모듈과 유사하게 동작해야 할 이유가 있는 건 아니지만..
제 경우에는 트래픽 정보가 유지 될 수 있다면 여러가지로 편리할 것 같습니다.

DB 등에 별도로 정보를 저장해서 유지하면서 비교해서 추가적으로 처리를 하면 가능할 듯도 하나
nginx-module-vts 모듈 자체적으로 정보 유지를 할 수 있는 방법이 있다면 정말 좋겠습니다.

**Comment by vozlt** [comment]
요구하시는 사항에 대한 필요성에 대해서 잘 이해 했습니다.
재시작후에도 기존 데이터를 복구 할 수 있는 방법을 생각해 보도록 하겠습니다.
감사합니다.

**Comment by hemith** [comment]
정말 고맙습니다!! 👍 👍 👍

**Comment by vozlt** [comment]
요구하시는 기능을 추가 했습니다.
테스트를 거의 하지 않아서 문제가 있는지 사용하시면서 확인해 볼 필요가 있습니다.
요구하시는 영구적인 데이터 보존을 위해 [vhost_traffic_status_dump](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_dump) 지시어를 사용하시면 됩니다.
해당 지시어의 두번째 인자에 백업 주기를 지정 할 수 있지만 기본적으로 정상적(SIGNAL)인 Nginx 종료시에 백업 주기와 상관없이 백업을 실행 하고 Nginx 를 종료 합니다.
감사합니다.

---

I added that feature as mentioned above.
I haven't much test yet. 😆
It is `vhost_traffic_status_dump` directive as follows:
```Nginx
http {
    vhost_traffic_status_zone;
    vhost_traffic_status_dump /var/log/nginx/vts.db;

    ...

    server {

        ...

    }
}
```
Please see the [vhost_traffic_status_dump](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_dump) directive for detailed usage.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/fc73722c5c9e5e0a48afa91a4da0b4a5f023ada9

**Comment by hemith** [comment]
답변이 많이 늦었습니다.
정말 정말 고맙습니다. 
테스트를 해 봤는데, 아주 잘 동작합니다!! 👍👍👍👍 💯 
혹시나 사용 중에 이슈가 발생하면 꼭 알려 드리겠습니다만
아무래도 잘만 동작할 것 같은 느낌이 드는군요!!! 😙
