### ISSUE TITLE
vhost_traffic_status_dump issue

### ISSUE THREAD

**Issue by arthurpro** [vozlt/nginx-module-vts#79]
I have VTS compiled as a dynamic module for Nginx 1.11.10
When I have the setting enabled `vhost_traffic_status_dump /var/log/nginx/vts.db;` Nginx has problem shuttinh down gracefully on CentOS 7 (didn't test other systems).
Though the `vts.db` file is created and looks good.
If I remove the setting, Nginx has no problem shutting down gracefully.

To be more specific, when `vhost_traffic_status_dump` is set then doing `kill -QUIT $PID` leads to the following situation:

```
root     103435  0.0  0.1 952936 15952 ?        Ss   Apr07   0:00 nginx: master process nginx
nginx    103436  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:00 nginx: worker process is shutting down
nginx    103437  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:01 nginx: worker process is shutting down
nginx    103438  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:00 nginx: worker process is shutting down
nginx    103439  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:01 nginx: worker process is shutting down
nginx    103440  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:00 nginx: worker process is shutting down
nginx    103441  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:00 nginx: worker process is shutting down
nginx    103443  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:00 nginx: worker process is shutting down
nginx    103445  0.0  0.2 1027244 19716 ?       Sl   Apr07   0:01 nginx: worker process is shutting down
```

These worker processes would never shut down.
As soon as I remove `vhost_traffic_status_dump` Nginx has no such issue.

**Comment by vozlt** [comment]
Thanks for reporting above problem.
I fixed it.
All processes will terminate within the dump period if NGINX received signal(SIGQUIT).
Please test it.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/bba6fe91ae1bd0ed22005172b5f55b56da7f1fa5

**Comment by arthurpro** [comment]
Unfortunately, I'm still seeing a problem, though the issue is fixed partially.
I recompiled the module from the latest commit and enabled `vhost_traffic_status_dump` setting.
On CentOS, by default SystemD waits for 5 seconds after sending SIGQUIT to Nginx. This is defined by `TimeoutStopSec=5` SystemD service setting in `nginx.service`.
With `vhost_traffic_status_dump` enabled when I do `systemctl restart nginx` it sends SIGQUIT, waits for 5 seconds for Nginx to quit gracefully and then starts new Nginx.
But still Nginx doesn't quit within 5 seconds when  `vhost_traffic_status_dump` is enabled. Also it makes Nginx unavailable for those 5 seconds because when you send SIGQUIT it stops accepting new connections.
After the graceful restart I can still see the following

```
nginx     32128  0.0  0.1 273856  4604 ?        S    10:32   0:00 nginx: worker process is shutting down
nginx     32129  0.0  0.1 273856  4368 ?        S    10:32   0:00 nginx: worker process is shutting down
```

This processes eventually quit but it takes more than 5 seconds.

Correct behavior for VTS would be to avoid blocking Nginx from quitting immediately.
Because in that state Nginx stops accepting new connections. And in a production environment 5 seconds of downtime is a big deal.

Thank you for your great work!

**Comment by vozlt** [comment]
Thanks for the detailed explanation.
I fixed it.
Please test it.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/bbc8ce621a80e7e6834905c1d32c985b9d392903

**Comment by arthurpro** [comment]
Works great now! Great work!
