### ISSUE TITLE
 status output enhancement

### ISSUE THREAD

**Issue by linbo** [vozlt/nginx-module-vts#80]
Hi,

Thanks for the nice module. Now I can monitor Nginx with more stats data.

For status output, could these enhancement provide in the future?

1. For server zone, could it use "IP:Port" as json key?  As my understanding, unique IP:Port refer to one server.  And I find if I didn't configure server_name, all server zone default name is "_". In this scenario, it won't separate multiple server zone.

2. For upstream zones, I prefer to add server zone information.  Like LVS, it will print the the whole proxy link, for example, client -> LVS(10.211.55.11:7778) -> backend (10.211.55.4:7778 ). Now I can't figure out upstream zone related to which server zone.

```
TCP  10.211.55.11:7778 wlc persistent 5
  -> 10.211.55.4:7778             Route   3      0          0
```

**Comment by vozlt** [comment]
Hi, the above requirements can be resolved with the following directives:
* [vhost_traffic_status_filter_by_host](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_by_host)
* [vhost_traffic_status_filter_by_set_key](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_by_set_key)

### Key by hostname
```Nginx
server {
  .
  .
  server_name _;
  vhost_traffic_status_filter_by_host on;
  .
  .
}
```

### Key by user-defined
```Nginx
server {
  .
  .
  vhost_traffic_status_filter_by_set_key $server_name:$server_port;

  location /backend {
    vhost_traffic_status_filter_by_set_key $upstream_addr backend::$server_name:$server_port;
    proxy_pass backend;
  }
}
```

 The `vhost_traffic_status_filter_by_set_key` directive can represent all variables using in nginx.

**Comment by linbo** [comment]
I test but no filter zones shows in json from http://nginx_IP:1234/status/format/json

Nginx:  nginx/1.10.2
nginx-module-vts:  lastest commit [bbc8ce621a80e7e6834905c1d32c985b9d392903](https://github.com/vozlt/nginx-module-vts/commit/bbc8ce621a80e7e6834905c1d32c985b9d392903)
OS: Red Hat Enterprise Linux Server release 7.2

```
$ cat app_component_cluster.conf.conf
upstream app_component_cluster {
    server backend_IP:8080 weight=5 max_fails=3 fail_timeout=30s;
}

server {
        listen   8080;
        vhost_traffic_status_filter_by_set_key $server_name:$server_port;

        location / {
            vhost_traffic_status_filter_by_set_key $upstream_addr backend::$server_name:$server_port;
            proxy_pass         http://app_component_cluster;
            proxy_redirect     off;
            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;

            proxy_connect_timeout      30s;
            proxy_send_timeout         30s;
            proxy_read_timeout         30s;

            proxy_buffer_size          4k;
            proxy_buffers              4 32k;
            proxy_busy_buffers_size    64k;
            proxy_temp_file_write_size 64k;
        }
    }

$ cat status.conf
server {
	listen 1234;
	server_name  statserver;

        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_bypass_stats on;
            vhost_traffic_status_display_format html;
        }
}
```

**Comment by vozlt** [comment]
It is expected to work well if put `vhost_traffic_status_filter_by_set_key` in location block.
Please test it.

`$ vi nginx.conf`
```Nginx
http {
    vhost_traffic_status_zone shared:vhost_traffic_status:8m;

    upstream backend {
        server 127.0.0.1:1234 weight=5 max_fails=3 fail_timeout=30s;
    }

    server {
        listen       1981 default_server backlog=65535;
        server_name  vts.example.org;
        
        location / {
            # Included in serverZones 
            vhost_traffic_status_filter_by_set_key $server_name:$server_port;
            
            # Included in filterZones
            vhost_traffic_status_filter_by_set_key $server_name:$server_port server;
            
            vhost_traffic_status_filter_by_set_key $upstream_addr backend::$server_name:$server_port;
            
            proxy_pass         http://backend;
        }   
    }   
    
    server {
        listen       1234 default_server backlog=65535;
        server_name  vts.example.org;
        
        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_bypass_stats on;
            vhost_traffic_status_display_format html;
        }   
    }   
}  
```

![2017-04-24 3 20 12](https://cloud.githubusercontent.com/assets/3648408/25324590/99b6597a-2901-11e7-82ba-81cf86db0c7a.png)

**Comment by linbo** [comment]
I see, if no http request for upstream, Filters Zone won't appear. 

Thanks.

**Comment by linbo** [comment]
@vozlt can upstreams info, like Response Time, Weight , show in Filters Zone?

**Comment by vozlt** [comment]
No, It can not.
