### ISSUE TITLE
Backend counters not uedateing

### ISSUE THREAD

**Issue by Menta2L** [vozlt/nginx-module-vts#81]
Probably is related to my setup but backend  traffic is not counting at all 

Nginx: nginx/1.11.13
nginx-module-vts: lastest 
OS:  CentOS Linux release 7.3.1611 (Core)

![vts](https://cloud.githubusercontent.com/assets/2862013/25307912/705a8f1a-27b2-11e7-8734-7b02de41a6f1.PNG)

Here is nginx configuration 

http {
    vhost_traffic_status_zone;
    vhost_traffic_status_filter_by_host on;

	upstream p1-backends {
		keepalive 100;
		server 10.1.111.66:80;
		server 10.1.111.67:80;
	}
	upstream p2-backends {
		keepalive 100;
		server 10.1.111.68:80;
		server 10.1.111.69:80;
	}
	upstream p3-backends {
		keepalive 100;
		server 10.1.111.70:80;
		server 10.1.111.71:80;
	}
	upstream p4-backends {
		keepalive 100;
		server 10.1.111.72:80;
		server 10.1.111.73:80;
	}

	server {
		listen              80;
		listen              443 ssl http2;
		server_name ~(?<subdomain>.*)\.example\.com$;
		ssl_certificate     /etc/nginx/ssl/star_example_com.crt;
		ssl_certificate_key /etc/nginx/ssl/star_example_com.key;
		ssl_dhparam  /etc/nginx/ssl/dhparam.pem;

		location / {
			proxy_pass http://$subdomain-backends;
			proxy_read_timeout     300;
			proxy_connect_timeout  300;
			proxy_http_version 1.1;
			proxy_set_header Connection "";
			proxy_set_header Accept-Encoding "";
			proxy_set_header Host $host;
		}
		location /status {
			vhost_traffic_status_bypass_limit on;
			vhost_traffic_status_display;
			vhost_traffic_status_display_format html;
		}
	}
}
`

and i  pass the traffic via all backends according to nginx accesslog 
`84.54.160.136 - [22/Apr/2017:20:53:27 +0300] "p3.example.com"->p3-backends->10.1.111.70:80 "GET /2014-11-23_2/900052o.jpg HTTP/2.0" 200(200) 94630/-(image/jpeg) 0.082(0.082)
84.54.160.136 - [22/Apr/2017:20:53:27 +0300] "p3.example.com"->p3-backends->10.1.111.71:80 "GET /2014-11-23_2/900258o.jpg HTTP/2.0" 200(200) 136871/-(image/jpeg) 0.094(0.094)
84.54.160.136 - [22/Apr/2017:20:53:38 +0300] "p4.example.com"->p4-backends->10.1.111.72:80 "GET /2015-01-05_2/1000136o.jpg HTTP/1.1" 200(200) 72772/-(image/jpeg) 0.001(0.001)
84.54.160.136 - [22/Apr/2017:20:53:38 +0300] "p2.example.com"->p2-backends->10.1.111.68:80 "GET /2015-01-05_2/1000145o.jpg HTTP/1.1" 200(200) 78355/-(image/jpeg) 0.002(0.002)
84.54.160.136 - [22/Apr/2017:20:53:38 +0300] "p2.example.com"->p2-backends->10.1.111.68:80 "GET /2015-01-05_2/1000143o.jpg HTTP/1.1" 200(200) 82497/-(image/jpeg) 0.002(0.002)
84.54.160.136 - [22/Apr/2017:20:53:38 +0300] "p2.example.com"->p2-backends->10.1.111.69:80 "GET /2015-01-05_1/1000276o.jpg HTTP/1.1" 200(200) 49455/-(image/jpeg) 0.002(0.002)
84.54.160.136 - [22/Apr/2017:20:53:38 +0300] "p1.example.com"->p1-backends->10.1.111.67:80 "GET /2015-01-05_1/1000277o.jpg HTTP/1.1" 200(200) 59383/-(image/jpeg) 0.005(0.005)`

**Comment by vozlt** [comment]
Thanks for reporting.
I tested it like as below without ssl configuration and it seems to work well.
Please check it again as follows:

```Nginx
http {
    vhost_traffic_status_zone shared:vhost_traffic_status:8m;
    vhost_traffic_status_filter_by_host on;

    upstream p1-backends {
        keepalive 100;
        server 127.0.0.1:8080;
    }

    upstream p2-backends {
        keepalive 100;
        server 127.0.0.1:8080;
    }

    server {
        listen       1981 default_server backlog=65535;
        server_name  ~(?<subdomain>.*)\.example\.org$;

        location / {
            proxy_pass http://$subdomain-backends;
            proxy_read_timeout     300;
            proxy_connect_timeout  300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Accept-Encoding "";
            proxy_set_header Host $host;
        }

        location /status {
            vhost_traffic_status_bypass_stats on;
            vhost_traffic_status_bypass_limit on;
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }

    }
}
```

`$ for i in {0..20}; do curl -H "Host: p$((RANDOM % 2 + 1)).example.org" http://127.0.0.1:1981/; done`

![2017-04-24 4 32 50](https://cloud.githubusercontent.com/assets/3648408/25326563/bbc72346-290b-11e7-8680-4dff87be3bdf.png)

**Comment by Menta2L** [comment]
Not sure why but its working like that :) 

Thanks and keep the good work !
