### ISSUE TITLE
upstream server shows 'up' when it's actually down

### ISSUE THREAD

**Issue by xczheng** [vozlt/nginx-module-vts#83]
In the stats html page, the "state" column shows the server "up" when it's actually down.
In the json output, it has "down": false,

Can this be fixed?

**Comment by linbo** [comment]
Check issue https://github.com/vozlt/nginx-module-vts/issues/44

**Comment by xczheng** [comment]
Thanks linbo. I wonder how we know if the server is currently down?

**Comment by linbo** [comment]
@xczheng   Nginx use [passive health check](http://nginx.org/en/docs/http/load_balancing.html#nginx_load_balancing_health_checks), the Nginx plus can configure  [active health check](https://www.nginx.com/resources/admin-guide/http-health-check/).  I don't know if variable or API exposed by Nginx for backend server status.
