### ISSUE TITLE
backend shows ::nogroups with defined backend servers group

### ISSUE THREAD

**Issue by xczheng** [vozlt/nginx-module-vts#84]
I have a backend group defined like this:
upstream servicebackend { 
...
}

But in the stats html page, it shows this backend group '::nogroups'. Is this a bug? I have some other groups and they show up correctly. The only difference is the servicebackend is used by 2 "server" while other backend groups are used by 1 "server".
Colin

**Comment by vozlt** [comment]
Hi, thanks for reporting.
Please let me know minimal nginx configuration and screenshot or JSON content to check.

**Comment by stefanmonkey** [comment]
I have a similar problem

nginx.conf like 

`
user  www www;
worker_processes  auto;
worker_rlimit_nofile 65535;
pid        /usr/local/ngx_openresty/nginx/var/nginxd.pid;
events {
    worker_connections  20480;
    use                 epoll;
    multi_accept        on;
}
http {
    charset       utf-8;
    include       mime.types;
    ...
    vhost_traffic_status_zone;
    
    ## notice!!! before upstream define
    include vhost/*.conf;
    
    upstream proxyaddr {
        ...
    }
    upstream proxy_uc {
        ...
    }
    upstream proxy_static {
        ...
    }
    upstream proxy_ssl {
        ...
    }
    upstream proxy_dyzyzz {
        ...
    }
    upstream proxy_ybadmin {
       ...
    }
    upstream proxy_adsys {
        ...
    }
    upstream proxy_wiki {
        ...
    }
    upstream proxy_dev-bbs {
        ...
    }
    upstream proxy_tornado {
        ...
    }
    
    upstream proxy_abcd {
        ...
    }
    include deny.ip; 
}
`

If some upstream is not use in vhost/*.conf, upstream can work ok. But upstream is use in vhost/*.conf, it show some backend in ::nogroups, others work ok.

but modify nginx.conf
`
...
upstream proxy_abcd {
        ...
    }

## notice!!! after upstream define
    include vhost/*.conf;
`

All things work perfectly as expect

**Comment by StrozhDima** [comment]
location /googleapis/ {
			internal;
			resolver 8.8.8.8 ipv6=off;
			proxy_pass https://www.googleapis.com/;
		}
... (not Upstream!!!) shows as Upstreams in section "::nogroups".
(Debian 9, nginx-module-vts latest version and nginx v1.10.3)
