### ISSUE TITLE
nginx general protection  process restart after  add vts module 

### ISSUE THREAD

**Issue by minminmsn** [vozlt/nginx-module-vts#88]
HI,
nginx -V
nginx version: nginx/1.12.0
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --with-http_gzip_static_module --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_stub_status_module --with-stream --with-stream_ssl_module --with-pcre --add-module=/usr/local/src/nginx-module-vts-0.1.6

tail -f /var/log/messages
Jul 18 14:04:39 ngx89-87 kernel: nginx[11047] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:40 ngx89-87 kernel: nginx[11025] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:41 ngx89-87 kernel: nginx[10974] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:42 ngx89-87 kernel: nginx[10931] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:43 ngx89-87 kernel: nginx[11049] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:44 ngx89-87 kernel: nginx[11053] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:45 ngx89-87 kernel: nginx[11044] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]
Jul 18 14:04:46 ngx89-87 kernel: nginx[11039] general protection ip:39aa87a1e8 sp:7ffc3ec56020 error:0 in libc-2.12.so[39aa800000+18a000]

After annotationed these ，it's ok now，but some nginx  servers don't need do these，I don't know why？

 ##vhost_traffic_status_zone;
 ##vhost_traffic_status_display;
 ##vhost_traffic_status_display_format html;

**Comment by vozlt** [comment]
Hi, Thanks for reporting.
It looks like it is not the nginx-module-vts latest version.
Please test with the nginx-module-vts latest version(v0.1.15).

**Comment by minminmsn** [comment]
ok ,i will test for you，tks!
