### ISSUE TITLE
If nginx overloaded - module is not responding

### ISSUE THREAD

**Issue by Profforgr** [vozlt/nginx-module-vts#9]
Hi.

This module is useful especially in case of DDoS attack or just traffic flow, but the problem is that if you load nginx by 100% - module stop responding.

Is there any ability to give a module highest priority, over other tasks, so it can continue to work even when load is 100%?

**Comment by vozlt** [comment]
I don't know if that's possible. (changing cpu priority of each module in nginx)
Frankly, It seems to be impossible so long as the connection processing methods(epoll, kqueue...) does not support.
You know, If you want to modify the process priority, can use "nice" command or setpriority() function.
It is possible to change the scheduling priority by using worker_priority directive in nginx.
But nginx is a single thread program. (using epoll or kqueue or ...)
All of modules in nginx is within one process. (in alphabetical order)
Anyway, I think that you should prevent the nginx load 100% by using various means. (limit_conn, limit_req...)

**Comment by Profforgr** [comment]
Thanks for detailed answer. Last version have threads support, however.

> Anyway, I think that you should prevent the nginx load 100% by using various means. (limit_conn, limit_req...)

Sure i am doing this.

**Comment by itpp16** [comment]
Sounds more like the LAN is saturated, maybe add another (management) LAN adapter and poll vhts from there.
If thats not enough you could think of using Lua with a Co-socket to pass on vhts traffic on a different port and via Lua lower the worker connections for a specific worker to keep it less occupied.
