### ISSUE TITLE
start even upstream host not resolvable

### ISSUE THREAD

**Issue by port22** [vozlt/nginx-module-vts#90]
Is it possible with this module to allow nginx to be started even if upstream hostnames are not resolveable at start?
That restriction is just deadly in a docker swarm environment where containers come and go and you can't rely on IPs, especially at provisioning  where nginx starts as the first service.

**Comment by vozlt** [comment]
Hi, This nginx-module-vts does not affect the host resolving.

**Comment by port22** [comment]
Thanks for you answer. I didn't meant to say that this module should affect the resolving itself, I was just curious if nginx will start with this module enabled if the/one/all upstream server(s) are not resolvable at startup.  Normally, nginx will not startup because of this but it should.

**Comment by vozlt** [comment]
That feature that can be started even if upstream hostnames are not resolveable is not supported in nginx-module-vts.
