### ISSUE TITLE
 ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone 

### ISSUE THREAD

**Issue by minminmsn** [vozlt/nginx-module-vts#93]
HI,
ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone 

client to  squid to nginx 

[root@ngx4 ~]# cat /etc/redhat-release 
CentOS release 6.9 (Final)
[root@ngx4 ~]# uname -a
Linux ngx4 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@ngx4 ~]# nginx -V
nginx version: nginx/1.12.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --with-http_gzip_static_module --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_stub_status_module --with-stream --with-stream_ssl_module --with-pcre --add-module=/usr/local/src/nginx-module-vts-0.1.15
[root@ngx4 ~]# tail -n 10 /usr/local/nginx/logs/error.log 
2017/08/06 17:22:02 [crit] 5360#0: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "ngx_http_vhost_traffic_status"
2017/08/06 17:22:02 [error] 5360#0: *180924550 shm_add_node::ngx_slab_alloc_locked() failed: used_size[618867], used_node[251] while logging request,

**Comment by minminmsn** [comment]
error.log  many  ***  access forbidden by rule,  maybe this lead to no memory in vhost_traffic_status_zone，modfify   vhost_traffic_status_zone shared:vhost_traffic_status:24m， looks good now.

**Comment by Dieken** [comment]
https://github.com/vozlt/nginx-module-vts/issues/95  I guess this issue is same.

It's better nginx-module-vts has some LRU mechanism to drop old entries in the filter set,  without this I have to use some cron job to periodically cleanup :-(

@vozlt,  could you share your thoughts? Thanks!

**Comment by toffstech** [comment]
how to drop old entries in the filter set?

**Comment by irsl** [comment]
I just encountered the very same issue:
2018/04/24 08:24:04 [crit] 32098#32098: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "ngx_http_vhost_traffic_status"

The sharedZones is at 60% of it's capacity:

name | ngx_http_vhost_traffic_status
maxSize | 1048575
usedSize | 616206
usedNode | 251

Please advise.

**Comment by vozlt** [comment]
It need to increase the shared memory size using vhost_traffic_status_zone.(The default shared memory size is 1M)
In most cases, the shared memory size used by nginx-module-vts does not increase much.
The shared memory size is increased pretty when using `vhost_traffic_status_filter_by_set_key` but if filter's keys are fixed(eg. the total number of the country code is about 240) it does not continuously increase.

If you use `vhost_traffic_status_filter_by_set_key` directive, set it as follows:
1. Set to more than **32M** shared memory size.(`vhost_traffic_status_zone shared:vhost_traffic_status:32m`)
2. If printed "`shm_add_node::ngx_slab_alloc_locked() failed`" in error_log, increase to more than (usedSize * 2).

Thanks.

**Comment by Dieken** [comment]
@vozlt 

I use "$uri $server_name" as filter key, since the $uri can be anything even some non-existed paths, the consumed memory keeps increasing,  so it's better to have a LRU mechanism to remove old entries that haven't new hits for a long time,  this isn't accurate for statistics but it's fair to trade less memory consumption.  Currently I use a cron job to periodically reset the statistics.

Thanks!

**Comment by vozlt** [comment]
@Dieken I have added a feature that limits the size of filters.
The filter key like "$uri $server_name" can be limit the size using that feature without cron job.
See the directive [vhost_traffic_status_filter_max_node](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_filter_max_node) for details.
Please test it.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/856663105061eeed18182c408a76dc27e0caaf1d
