### ISSUE TITLE
The configuration is correct, but nothing can be found

### ISSUE THREAD

**Issue by timosir** [vozlt/nginx-module-vts#94]
hi，vozlt
      my nginx version :nginx/1.8.1
      Centeos :CentOS Linux release 7.2.1511 
      The configuration file is as follows：
     http {
       vhost_traffic_status_zone;

       include   xxx.conf;
  }

   xxx.conf:
    server {
 
        server_name www.domain.com;
          location / {
           { 
           proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header Accept-Encoding 'gzip';
            proxy_pass http://xxx$uri$is_args$args;
        }

        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }
    }
}
 
when i am request  http://domain.com/status      ,always   404 status ,

**Comment by vozlt** [comment]
Hi, Still having problems?
