### ISSUE TITLE
I'm getting a lot or critical error log messages

### ISSUE THREAD

**Issue by geirarnesen** [vozlt/nginx-module-vts#95]
Anything I can do here?

`2017/08/14 08:55:52 [crit] 71#71: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "ngx_http_vhost_traffic_status"
2017/08/14 08:55:53 [crit] 71#71: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "ngx_http_vhost_traffic_status"
2017/08/14 08:55:53 [error] 71#71: *1214089 shm_add_node::ngx_slab_alloc_locked() failed: used_size[617070], used_node[251] while logging request, client: 127.0.0.1, server: snt-drfront-prod.s3-website-eu-west-1.amazonaws.com, request: "GET /sa/data/front-14.revision HTTP/1.1", upstream: "http://52.218.64.42:80/sa/data/front-14.revision", host: "drfront-prod.schibsted.tech"
2017/08/14 08:55:53 [error] 71#71: *1214089 shm_add_upstream::shm_add_node("UA^_52.218.64.42:80") failed while logging request, client: 127.0.0.1, server: snt-drfront-prod.s3-website-eu-west-1.amazonaws.com, request: "GET /sa/data/front-14.revision HTTP/1.1", upstream: "http://52.218.64.42:80/sa/data/front-14.revision", host: "drfront-prod.schibsted.tech"
2017/08/14 08:55:53 [crit] 71#71: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "ngx_http_vhost_traffic_status"
2017/08/14 08:55:53 [error] 71#71: *1214077 shm_add_node::ngx_slab_alloc_locked() failed: used_size[617070], used_node[251] while logging request, client: 127.0.0.1, server: farticles-lind-us.herokuapp.com, request: "GET / HTTP/1.1", upstream: "https://23.21.142.10:443/", host: "127.0.0.1"
2017/08/14 08:55:53 [error] 71#71: *1214077 shm_add_upstream::shm_add_node("UA^_23.21.142.10:443") failed while logging request, client: 127.0.0.1, server: farticles-lind-us.herokuapp.com, request: "GET / HTTP/1.1", upstream: "https://23.21.142.10:443/", host: "127.0.0.1"`

**Comment by timosir** [comment]
may be your nginx  version is too old

**Comment by vozlt** [comment]
Hi, It probably need to increase the shared memory size using [`vhost_traffic_status_zone`](https://github.com/vozlt/nginx-module-vts#vhost_traffic_status_zone).(The default shared memory size is 1M)

As following:
`vhost_traffic_status_zone shared:vhost_traffic_status:8m`
