### ISSUE TITLE
[Optimize??] The data could not reflect real service request even the directory 'vhost_traffic_status_bypass_limit' and 'vhost_traffic_status_bypass_limit' on

### ISSUE THREAD

**Issue by regardfs** [vozlt/nginx-module-vts#96]
Hi,
I am using below config to enable status and aimed at not adding  /status request number  to total ones:
```
    location /status {
    	    access_log off;
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
            vhost_traffic_status_bypass_limit on;
            vhost_traffic_status_bypass_stats on;
    	    allow 127.0.0.1;
            allow 172.0.0.0/8;
            deny all;
        }
    }
```
But  you could find that in `Server Main` zone, the request statistics still increase , but not the `Server Zones`, So I wonder how to eliminate this statistics forever??
![image](https://user-images.githubusercontent.com/8295227/29815940-f2fcb3f2-8ce4-11e7-80ef-e72ad2c6f065.png)

Thanks a ton

**Comment by regardfs** [comment]
Anyone ？？

**Comment by vozlt** [comment]
Hi, that statistics(Connections, Requests) in **Server Main** can not be excluded because it implemented in nginx core and then nginx-module-vts module just takes it and uses it.
See the [ngx_http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html).
Thanks.
