### ISSUE TITLE
[Q] Add 'responseMsec' metric for filterZone (upstream like)

### ISSUE THREAD

**Issue by mbobakov** [vozlt/nginx-module-vts#99]
Hello. 
Is it technically possible to add 'responseMsec' metric for filterZones which added by the 'vhost_traffic_status_filter_by_set_key' directive? 
I think it will be cool to add it

**Comment by vozlt** [comment]
The `requestMsec` in filterZones and serverZones is the same meaning as `requestMsec` in upstreamZones while the `responseMsec` in upstreamZones is only for upstream backend servers.
Please give an example of why you need it.
Thanks.

#### serverZones|filterZones
* requestMsec
  * The average of request processing times in milliseconds.

#### upstreamZones
* requestMsec
  * The average of request processing times including upstream in milliseconds.

* responseMsec
  * The average of only upstream response processing times in milliseconds.
